#!/usr/bin/env python3
"""Build the checked-in AlarmQuest ko -> en/ja runtime catalogs.

This utility is intentionally separate from the Android build. It scans Korean Kotlin literals,
protects Kotlin/story placeholders, translates in batches with a local CTranslate2 M2M-100 model,
and emits deterministic Base64 TSV resources. The app never downloads or runs a translation model.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
from pathlib import Path

KOREAN = re.compile(r"[가-힣]")
STANDARD_STRING = re.compile(r'"((?:\\.|[^"\\])*)"')
TRIPLE_STRING = re.compile(r'"""(.*?)"""', re.DOTALL)
PLAIN_PLACEHOLDER = re.compile(r"\{[A-Za-z][A-Za-z0-9_]*}")
LEGACY_TOKEN = re.compile(r"ZXQPH([1-9][0-9]*)ZXQ")
MODEL_TOKEN = re.compile(r"\[990000([1-9][0-9]*)]")
CATALOG_TOKEN = re.compile(r"\{\{([1-9][0-9]*)}}")

NON_DISPLAY_LITERALS = {
    "^제([1-9][0-9]*)구역 관문지기 · (.+)$",
    "${definition.baseName}의 $form",
    "의 $form",
    "{{1}}의 {{2}}",
    "^초월 [1-9][0-9]*단식(?= )",
    "초월 ([1-9][0-9]*)단식",
    "매사냥",
    "지휘관",
    "사제",
    "성전",
    "수호",
    "신관",
    "왕실",
    "현자",
    "관찰 일지",
    "그림자 ",
    "둥지 부스러기",
    "먹이 흔적",
    "발자국 석고",
    "별빛 ",
    "생태 기록",
    "선혈 표본",
    "수호 ",
    "왕실 ",
    "외피 조각",
    "용맹 ",
    "음영 스케치",
    "이동로 표식",
    "잔해",
    "재가루",
    "조직 표본",
    "탈피 조각",
    "활동 기록",
    "흔적",
}


MANUAL_EN = {
    "널 플레이잉": "Null Playing",
    "플레이하지 않아도, 모험은 진행 중.": "Not playing. Still progressing.",
    "설정": "Settings",
    "언어": "Language",
    "표시 언어를 선택하세요": "Choose your display language",
    "영어": "English",
    "일본어": "Japanese",
    "한국어": "Korean",
    "게임 화면으로 돌아가기": "Back to game",
    "오프라인 모험 소진 알림": "Offline adventure alerts",
    "오프라인 모험 충전 소진": "Offline adventure time depleted",
    "잔여 시간이 0이 되면 기기 알림": "Notify me when time runs out",
    "소진 알림 꺼짐": "Depletion alerts are off",
    "기기 알림 권한을 허용해야 알림을 받을 수 있습니다.": "Allow notifications on your device to receive alerts.",
    "기기 알림 권한이 필요합니다.": "Notification permission is required.",
    "시스템 설정에서 기기 알림 권한이 꺼져 있습니다.": "Notification permission is blocked in system settings.",
    "시스템 설정에서 앱 알림이 꺼져 있습니다.": "App notifications are off in system settings.",
    "시스템 알림 설정 열기": "Open system notification settings",
    "시스템 알림 설정을 열지 못했습니다.": "Couldn't open system notification settings.",
    "모험가 관리": "Adventurer management",
    "모험가": "Adventurer",
    "모험가 선택 화면으로": "Go to adventurer selection",
    "모험가 선택 화면으로 이동": "Go to adventurer selection",
    "{{1}}. {{2}}. 모험가 선택 화면으로 이동": "{{1}}. {{2}}. Go to adventurer selection.",
    "모험가 화면으로 돌아가기": "Back to adventurer screen",
    "모험가 삭제": "Delete adventurer",
    "모험가를 삭제할까요?": "Delete this adventurer?",
    "게임 정보": "Game info",
    "개인정보처리방침": "Privacy Policy",
    "개인정보처리방침을 열지 못했습니다.": "Couldn't open the privacy policy.",
    "닫기": "Close",
    "익명 사용자 ID를 확인할 수 없습니다": "Couldn't verify the anonymous user ID",
    "저장된 익명 사용자와 서버 사용자가 일치하지 않습니다": "The stored anonymous user doesn't match the server user",
    "광고 개인정보 선택": "Ad privacy choices",
    "광고 개인정보 설정을 열지 못했습니다.": "Couldn't open ad privacy settings.",
    "버전 {{1}}": "Version {{1}}",
    "설정 화면에서도 자동 모험은 계속 진행됩니다.": "Auto-adventure continues while Settings is open.",
    "{{1}}의 오프라인 모험 시간이 모두 소진되었습니다.": "{{1}}'s offline adventure time has run out.",
    "메인": "Home",
    "캐릭터": "Hero",
    "장비": "Gear",
    "가방": "Bag",
    "퀘스트": "Quests",
    "자동 진행 중": "Auto-progressing",
    "전투력": "Power",
    "전투력 {{1}}": "Power {{1}}",
    "레벨 {{1}}": "Level {{1}}",
    "이어하기 ›": "Continue ›",
    "현재 모험": "Current quest",
    "오프라인 잔여": "Offline left",
    "내 순위": "My rank",
    "전체 랭킹": "Overall ranking",
    "호칭": "Title",
    "순위 없음": "Unranked",
    "순위 미집계": "Unranked",
    "순위 집계 중": "Ranking pending",
    "유일한 왕좌": "Sole Sovereign",
    "왕좌에 닿은 자": "One Who Reached the Throne",
    "천상의 수호자": "Celestial Guardian",
    "전설의 선봉": "Legendary Vanguard",
    "별을 베는 자": "Starcleaver",
    "불굴의 정복자": "Unyielding Conqueror",
    "황금의 개척자": "Golden Pioneer",
    "새벽의 추적자": "Dawn Tracker",
    "은빛의 영웅": "Silver Hero",
    "별빛의 계승자": "Heir to the Starlight",
    "황금의 선구자": "Golden Trailblazer",
    "은빛 추적자": "Silver Tracker",
    "청동 길잡이": "Bronze Guide",
    "별빛의 도전자": "Starlit Challenger",
    "새벽의 모험가": "Dawn Adventurer",
    "여정을 걷는 자": "Wayfarer",
    "다시 시도": "Retry",
    "확인": "Confirm",
    "보기": "View",
    "랭킹을 불러오는 중": "Loading rankings",
    "모험가 랭킹": "Adventurer rankings",
    "능력치": "Stats",
    "능력치 안내": "Stat Guide",
    "모든 직업에 적용되는 효과입니다.": "These benefits apply to every class.",
    "직업의 주·보조 능력치는 공격력·전투력과 기본 스킬 발동률에도 영향을 줍니다.": "Your class's primary and secondary stats also affect damage, combat power, and base skill trigger chance.",
    "STR · 힘": "STR · Strength",
    "CON · 체력": "CON · Constitution",
    "DEX · 민첩": "DEX · Dexterity",
    "INT · 지능": "INT · Intelligence",
    "WIS · 지혜": "WIS · Wisdom",
    "CHA · 매력": "CHA · Charisma",
    "HP MAX · 최대 HP": "HP MAX · Maximum HP",
    "MP MAX · 최대 MP": "MP MAX · Maximum MP",
    "가방에 더 많은 전리품을 담을 수 있습니다.": "Carry more loot in your bag.",
    "오프라인 모험시간이 늘어나고, 최대 HP 성장에 도움이 됩니다.": "Adventure offline for longer and gain more maximum HP as you grow.",
    "몬스터를 더 빨리 찾습니다.": "Find monsters faster.",
    "스킬이 더 자주 발동하며, 최대 MP 성장에 도움이 됩니다.": "Trigger skills more often and gain more maximum MP as you grow.",
    "전리품을 더 높은 가격에 판매합니다.": "Sell loot for more gold.",
    "CON에 따라 성장하는 최대 체력입니다.": "Your maximum health, which grows based on CON.",
    "INT와 WIS에 따라 성장하는 최대 마나입니다.": "Your maximum mana, which grows based on INT and WIS.",
    "스킬": "Skills",
    "장착 장비": "Equipped gear",
    "현재 깊이": "Current depth",
    "최고 완주 깊이": "Deepest clear",
    "지난 모험담": "Past tales",
    "완결된 이야기": "Completed stories",
    "완결": "Completed",
    "전리품": "Loot",
    "획득 완료": "Collected",
    "모험의 서막": "Adventure prologue",
    "새로운 모험": "New adventure",
    "모험가 생성": "Create adventurer",
    "모험가 이름 (2~8자)": "Adventurer name (2–8 chars)",
    "아직 모험가가 없습니다": "No adventurer yet",
    "첫 모험가를 만들어 멈춰 있던 세계를 깨워 보세요.": "Create your first adventurer and awaken the frozen world.",
    "직업 선택": "Choose a class",
    "능력치 굴림": "Stat Roll",
    "이 능력치로 모험 시작": "Start adventure with these stats",
    "주 능력치": "Primary",
    "보조 능력치": "Secondary",
    "다음 모험가 슬롯 · Lv.{{1}}에 영구 해금": "Next adventurer slot · Permanently unlocks at Lv.{{1}}",
    "아래로 스크롤": "Scroll down",
    "아래에 더 많은 모험 기록이 있습니다": "More adventure records below",
    "다시 굴리기": "Reroll",
    "이전": "Previous",
    "다음": "Next",
    "나중에": "Later",
    "업데이트하기": "Update",
    "계속하려면 업데이트가 필요합니다.": "Update required to continue.",
    "업데이트 페이지를 열지 못했습니다": "Couldn't open the update page",
    "다시 불러오기": "Try again",
    "모험 기록 확인 필요": "Adventure record needs attention",
    "모험 기록을 불러오는 중": "Loading adventure records",
    "지난 시간의 모험을 계산하는 중": "Calculating time away",
    "모험 기록을 정리하는 중": "Saving adventure records",
    "모험을 시작하는 중": "Starting the adventure",
    "모험 기록을 확인하는 중": "Checking adventure records",
    "모험 기록을 안전하게 준비하고 있습니다": "Preparing your adventure records safely",
    "오프라인 모험 충전": "Offline adventure time",
    "바로 충전": "Charge Now",
    "충전 완료": "Charged",
    "가득 차면 자동 귀환": "Returns when full",
    "보유한 스킬이 없습니다.": "No skills learned yet.",
    "첫 전리품을 기다리는 중입니다.": "Waiting for your first loot.",
    "타이틀로 돌아가기": "Back to title",
    "모험가 선택으로 돌아가기": "Back to adventurer selection",
    "캐릭터 화면으로 돌아가기": "Back to character screen",
    "상단 배너 광고 320x50dp": "Top banner ad, 320 by 50 dp",
    "전사": "Warrior",
    "도적": "Rogue",
    "순찰자": "Ranger",
    "마법사": "Mage",
    "성직자": "Cleric",
    "성기사": "Paladin",
    "파이터": "Fighter",
    "시프": "Thief",
    "레인져": "Ranger",
    "레인저": "Ranger",
    "메이지": "Mage",
    "클래릭": "Cleric",
    "팔라딘": "Paladin",
    "무기": "Weapon",
    "머리": "Head",
    "몸": "Body",
    "손": "Hands",
    "발": "Feet",
    "장신구": "Accessory",
    "일반": "Normal",
    "고급": "Uncommon",
    "희귀": "Rare",
    "영웅": "Epic",
    "전설": "Legendary",
    "신화": "Mythic",
    "정예": "Elite",
    "보스": "Boss",
    "서막": "Opening",
    "전투": "Battle",
    "아이템 획득": "Looting",
    "귀환": "Returning",
    "장비 선별": "Selecting gear",
    "전리품 판매": "Selling loot",
    "장비 정비": "Gear maintenance",
    "구매 결과": "Purchase result",
    "장비 검토": "Reviewing gear",
    "출정": "Departing",
    "물리": "Physical",
    "화염": "Fire",
    "냉기": "Ice",
    "번개": "Lightning",
    "비전": "Arcane",
    "암흑": "Dark",
    "맹독": "Poison",
    "바람": "Wind",
    "대지": "Earth",
    "신성": "Holy",
    "우주": "Cosmic",
    "내 순위 {{1}}위, {{2}}, 호칭 {{3}}, 전투력 {{4}}": "My rank: {{1}}, {{2}}, title: {{3}}, power: {{4}}",
    "내 순위 {{1}}, {{2}}, 호칭 {{3}}, 전투력 {{4}}": "My rank: {{1}}, {{2}}, title: {{3}}, power: {{4}}",
    " {{1}}. {{2}}회 중 {{3}}회 완료. 자동 진행 중.": " {{1}}. {{3}} of {{2}} completed. Auto-progressing.",
    "랭킹 참가까지 레벨 20, 현재 레벨 {{1}}, {{2}}": "Level 20 required for ranking; current level {{1}}, {{2}}",
    "{{1}}, {{2}}, 레벨 {{3}}, 전투력 ": "{{1}}, {{2}}, level {{3}}, power ",
    "{{1}} 스킬 {{2}}개 · 스킬을 누르면 즉시 재생": "{{1}} skills: {{2}} · Tap a skill to play it",
    "제{{1}}구역 · 제{{2}}관문 · {{3}}": "Sector {{1}} · Gate {{2}} · {{3}}",
    "제{{1}} 수문장": "Gatekeeper {{1}}",
    "{{1}} · 장비력 {{2}} · {{3}}": "{{1}} · gear power {{2}} · {{3}}",
    "{{1}}, {{2}}, 레벨 {{3}}, ": "{{1}}, {{2}}, level {{3}}, ",
    "{{1}} · {{2}}막  {{3}}": "{{1}} · Act {{2}}  {{3}}",
    "{{1}}, {{2}}막 {{3}}.": "{{1}}, Act {{2}} {{3}}.",
    "{{1}}, 스킬 경험치 {{2}}": "{{1}}, skill XP {{2}}",
    "호칭 {{1}}, 전투력 {{2}}": "Title {{1}}, power {{2}}",
    "{{1}}회 중 {{2}}회 완료": "{{2}} of {{1}} completed",
    "{{1}}위, ": "Rank {{1}}, ",
    "현재 장면 {{1}}, {{2}}": "Current scene {{1}}, {{2}}",
    "제{{1}}권 제{{2}}장": "Volume {{1}}, Chapter {{2}}",
    "제{{1}}권 · {{2}}": "Book {{1}} · {{2}}",
    "제{{1}}구역 관문지기 · {{2}}": "Sector {{1}} Gatekeeper · {{2}}",
    "제{{1}}구역 · {{2}}": "Sector {{1}} · {{2}}",
    "{{1}}막 · {{2}}": "Act {{1}} · {{2}}",
    "제{{1}}장  {{2}}": "Chapter {{1}}  {{2}}",
    "매의 급강하": "Hawk Dive",
    "검댕 뿔토끼": "Sooty Horned Rabbit",
    "{{1}}의 둥지 부스러기": "{{1}} Nest Debris",
    "{{1}}의 발자국 석고": "{{1}} Footprint Cast",
    "거미 독낭": "Spider Venom Sac",
    "그림자보다 빠르게": "Faster Than Shadow",
    "깊이의 무게": "Weight of the Depths",
    "돌아오지 않은 순찰대": "The Patrol That Never Returned",
    "재가 내리는 우물": "The Ashfall Well",
    "종이 새가 물어온 이름": "The Name Brought by the Paper Bird",
    "문 없는 예배당": "Chapel Without a Door",
    "밀수꾼의 정직한 지도": "The Smuggler's Honest Map",
    "적의 깃발 아래": "Beneath the Enemy's Banner",
    "잠들지 않는 성벽": "The Unsleeping Rampart",
    "서로 다른 두 개의 명령": "Two Conflicting Orders",
    "검은 종의 행렬": "Procession of Black Bells",
    "재의 성채": "Ashen Citadel",
    "새벽을 삼킨 왕": "The King Who Devoured Dawn",
    "국경에 다시 뜬 해": "The Sun Rises Again over the Border",
    "유리 잎이 가리킨 북쪽": "The North Pointed to by the Glass Leaf",
    "발자국을 기억하는 숲": "The Forest That Remembers Footsteps",
    "창문 속에 갇힌 목소리": "The Voice Trapped in the Window",
    "사라진 봄의 지도": "Map of the Vanished Spring",
    "베른에게 닿지 못한 답장": "The Reply That Never Reached Bern",
    "아무도 늙지 않는 정원": "The Garden Where No One Ages",
    "도둑맞은 봄의 물": "Stolen Springwater",
    "서로를 닮은 두 사람": "Two Alike",
    "백야가 시작된 탑": "The Tower Where the White Night Began",
    "유리 심장의 진실": "The Truth of the Glass Heart",
    "깨지는 숲의 밤": "The Night the Forest Shattered",
    "유리 숲의 첫 번째 봄": "The Glass Forest's First Spring",
    "전령의 부탁: 돌아오지 않은 순찰대를 찾아 국경 마을의 피난로를 열어라.": "A Messenger's Request: Find the missing patrol and clear the border village's escape route.",
    "지워진 수신인": "Erased Recipient",
    "쫓기는 전령": "Fleeing Messenger",
    "종지기 오르반": "Bellkeeper Orban",
    "벽뿐인 예배당": "Chapel of Walls",
    "세관 아래의 길": "Path Beneath the Customs House",
    "돌아오지 못한 밀수꾼": "The Smuggler Who Never Returned",
    "서문을 지킨 이름들": "Names That Held the West Gate",
    "같은 날의 명령서": "Orders Issued the Same Day",
    "사라진 서기관": "Vanished Scribe",
    "보호라는 변명": "Protection as an Excuse",
    "성채로 향한 이름": "A Name Bound for the Citadel",
    "천 아래의 종": "Bells Beneath the Cloth",
    "끊어진 추격로": "Severed Pursuit Route",
    "빈 병영": "Empty Barracks",
    "잘못된 수호자": "False Guardian",
    "꺼진 하늘": "Extinguished Sky",
    "되돌아온 길들": "Paths Reopened",
    "함께 울린 종": "Bells Rung Together",
    "돌아온 새벽": "Dawn Restored",
    "세 번의 불빛": "Three Flashes",
    "지도 밖의 북방길": "Northern Road Beyond the Map",
    "앞서 간 발자국": "Footprints Ahead",
    "어제인 채 남은 야영지": "Campsite Trapped in Yesterday",
    "이름을 잃은 대답": "The Answer That Lost Its Name",
    "계절 지하실의 파수자": "Seasonal Cellar Sentinel",
    "얼어붙은 우편낭": "Frozen Mailbag",
    "도착하지 않은 구원": "Rescue That Never Arrived",
    "답장을 삼킨 봉인": "Seal That Swallowed the Reply",
    "멈춘 정오": "Frozen Noon",
    "되풀이되는 동의": "Repeated Consent",
    "거꾸로 흐르는 강": "Reverse-Flowing River",
    "유리를 만드는 물레": "Glassmaking Waterwheel",
    "빙결 수문장": "Frozen Sluice Gatekeeper",
    "해 지지 않는 계단": "Stairway of Eternal Day",
    "세 불빛의 주인": "Master of the Three Lights",
    "틀린 음의 합주": "Ensemble of Wrong Notes",
    "길이 된 봄물": "Springwater That Became a Road",
    "나이테 회랑": "Tree-Ring Gallery",
    "숨 쉬는 길": "Breathing Path",
    "드러난 서고": "Exposed Stacks",
    "잠든 공명핵": "Dormant Resonance Core",
    "걸어 다니는 쇳조각": "Walking Scrap Metal",
    "화로의 약탈자": "Furnace Raider",
    "봉인된 화로": "Sealed Furnace",
    "기억을 흐리는 꽃가루": "Memory-Clouding Pollen",
    "재꽃을 지키는 것": "Guardian of the Ash Blossom",
    "꽃 속의 얼굴": "Face Within the Flower",
    "지상 흙의 원": "Circle of Surface Soil",
    "방향을 잃은 첫 단": "The First Step Gone Astray",
    "나선의 끝문": "Spiral's Final Gate",
    "{{1}}, {{2}}, 레벨 {{3}}, 전투력 {{4}}, 현재 모험 {{5}}, 오프라인 모험 잔여 {{6}}퍼센트, 이어하기": "{{1}}, {{2}}, level {{3}}, power {{4}}, current quest {{5}}, offline adventure {{6}} percent remaining, continue",
    "죽은 자의 명령": "Order of the Dead",
    "{{1}}에게 도착한 다음 날의 명령": "The Next Day's Order Sent to {{1}}",
    "죽은 자에게 도착한 다음 날의 명령": "The Next Day's Order Sent to the Dead",
    "비에 젖지 않는 종이 새가 날아와 {{1}}의 발치에서 스스로 펼쳐졌다.": "A paper bird untouched by the rain flew in and unfolded itself at {{1}}'s feet.",
    "펼쳐짐. 두 번 탭하여 접기.": "Expanded. Double-tap to collapse.",
    "접힘. 두 번 탭하여 펼치기.": "Collapsed. Double-tap to expand.",
    "아직 시작되지 않음.": "Not started yet.",
    "앞의 장면이 아직 끝나지 않음.": "The previous scene is not yet complete.",
    "모험식": "Adventuring",
    "정규군식": "Standard-Issue",
    "개량 전투식": "Improved Combat",
    "숙련 전투식": "Veteran Combat",
    "기사단식": "Order-Issue",
    "전승식": "Heirloom",
    "용골 강화": "Dragonbone-Reinforced",
    "성유 각인": "Holy-Oil-Inscribed",
    "마정석": "Mana Crystal",
    "성역식": "Sanctuary-Forged",
    "심층제": "Depth-Forged",
    "천공식": "Skyforged",
    "운명식": "Fatebound",
    "뿔투구": "Horned Helm",
    "지휘관 투구": "Commander's Helm",
    "전사 건틀릿": "Warrior Gauntlets",
    "지휘관 판금화": "Commander's Plate Boots",
    "용맹 브로치": "Valor Brooch",
    "전사 허리띠": "Warrior Belt",
    "파이터 투구": "Fighter Helm",
    "파이터 갑옷": "Fighter Armor",
    "파이터 건틀릿": "Fighter Gauntlets",
    "파이터 장화": "Fighter Boots",
    "파이터 허리띠": "Fighter Belt",
    "시프 후드": "Thief Hood",
    "시프 가죽옷": "Thief Leathers",
    "시프 장갑": "Thief Gloves",
    "시프 장화": "Thief Boots",
    "시프 인장": "Thief Sigil",
    "야행 머리띠": "Nightstalker Headband",
    "독니 목걸이": "Venom-Fang Necklace",
    "은신 브로치": "Concealment Brooch",
    "순찰자 두건": "Ranger Hood",
    "매사냥 모자": "Falconer's Hat",
    "순찰자 사냥복": "Ranger Hunting Garb",
    "레인져 창": "Ranger Spear",
    "레인져 두건": "Ranger Hood",
    "레인져 사냥복": "Ranger Hunting Garb",
    "레인저 창": "Ranger Spear",
    "레인저 두건": "Ranger Hood",
    "레인저 사냥복": "Ranger Hunting Garb",
    "매사냥 코트": "Falconer's Coat",
    "사냥 장갑": "Hunting Gloves",
    "활시위 손목띠": "Bowstring Wristguard",
    "매사냥 장갑": "Falconer's Gloves",
    "순찰 전투화": "Patrol Boots",
    "매눈 목걸이": "Hawk-Eye Necklace",
    "순찰 인장": "Patrol Sigil",
    "마도사 로브": "Mage Robe",
    "마도사 신발": "Mage Shoes",
    "메이지 관": "Mage Circlet",
    "메이지 로브": "Mage Robe",
    "메이지 신발": "Mage Shoes",
    "마력 장갑": "Mana Gloves",
    "현자 손갑": "Sage's Gauntlets",
    "수정 목걸이": "Crystal Necklace",
    "별빛 덧신": "Starlit Slippers",
    "성가대 모자": "Choir Cap",
    "성유 손목띠": "Holy-Oil Wristband",
    "신관 비단신": "Priest's Silk Shoes",
    "성상 목걸이": "Holy-Icon Necklace",
    "성가 브로치": "Hymn Brooch",
    "클래릭 관": "Cleric Circlet",
    "클래릭 로브": "Cleric Robe",
    "클래릭 완갑": "Cleric Vambraces",
    "클래릭 장화": "Cleric Boots",
    "클래릭 허리띠": "Cleric Belt",
    "심판 망치": "Judgment Hammer",
    "성기사 투구": "Paladin Helm",
    "성기사 갑옷": "Paladin Armor",
    "성기사 건틀릿": "Paladin Gauntlets",
    "수호 철제신": "Guardian Iron Boots",
    "성휘 목걸이": "Sacred-Light Necklace",
    "성전 브로치": "Crusade Brooch",
    "성기사 허리띠": "Paladin Belt",
    "팔라딘 투구": "Paladin Helm",
    "팔라딘 갑옷": "Paladin Armor",
    "팔라딘 건틀릿": "Paladin Gauntlets",
    "팔라딘 장화": "Paladin Boots",
    "팔라딘 허리띠": "Paladin Belt",
    "낡은": "Worn",
    "거친": "Rough",
    "소박한": "Simple",
    "손질한": "Well-Kept",
    "튼튼한": "Sturdy",
    "빛바랜": "Faded",
    "상처 입은": "Wounded",
    "길 잃은": "Lost",
    "배고픈": "Hungry",
    "날카로운": "Sharp",
    "낮게 웅크린": "Crouching Low",
    "눈 밝은": "Keen-Eyed",
    "제멋대로인": "Unruly",
    "숨을 죽인": "Lurking Quietly",
    "빠른": "Swift",
    "노련한": "Seasoned",
    "무리를 이탈한": "Strayed from the Pack",
    "밤을 노리는": "Prowling at Night",
    "한쪽 눈의": "One-Eyed",
    "거친 털의": "Rough-Coated",
    "소리 없는": "Silent",
    "흔적을 감춘": "Trackless",
    "종이 새를 좇는": "Chasing the Paper Bird",
    "니아의 길을 좇는 자": "Follower of Nia's Path",
    "쫓기는 편지의 탈취자": "Raider of the Hunted Letter",
    "투명 껍질 딱정벌레": "Transparent-Shelled Beetle",
    "투명하게 굳은 껍질의": "With a Hardened Transparent Shell",
    "봉인 나방": "Sealed Moth",
    "{{1}}막": "Act {{1}}",
    "{{1}}의 잔해": "Remains of {{1}}",
    "{{1}} 표본": "{{1}} Specimen",
    "{{1}}의 흔적": "Traces of {{1}}",
    "{{1}}의 외피 조각": "Shell Fragment of {{1}}",
    "{{1}}의 조직 표본": "Tissue Sample of {{1}}",
    "{{1}}의 둥지 부스러기": "{{1}} Nest Debris",
    "{{1}}의 발자국 석고": "{{1}} Footprint Cast",
    "{{1}}의 먹이 흔적": "Feeding Traces of {{1}}",
    "{{1}}의 재가루": "Ash Residue from {{1}}",
    "{{1}}의 생태 기록": "Field Notes on {{1}}",
    "{{1}}의 활동 기록": "Field Notes on {{1}}",
    "{{1}}의 탈피 조각": "Shed Skin of {{1}}",
    "{{1}}의 선혈 표본": "Fresh Blood Sample of {{1}}",
    "{{1}}의 음영 스케치": "Silhouette Sketch of {{1}}",
    "{{1}}의 이동로 표식": "Route Marker for {{1}}",
    "{{1}}의 관찰 일지": "Observation Log of {{1}}",
    "{{1}} 발견": "{{1}} Spotted",
    "발견했습니다": "Spotted",
    "‘{{1}}’의 레벨, 장비, 가방, 기술, 퀘스트를 포함한 모든 모험 기록이 영구 삭제됩니다.\n\n삭제한 기록은 복구할 수 없습니다.": "All adventure data for ‘{{1}}’—including level, gear, bag, skills, and quests—will be permanently deleted.\n\nDeleted data cannot be recovered.",
    "‘{{1}}’의 레벨, 장비, 가방, 스킬, 퀘스트를 포함한 모든 모험 기록이 영구 삭제됩니다.\n\n삭제한 기록은 복구할 수 없습니다.": "All adventure data for ‘{{1}}’—including level, gear, bag, skills, and quests—will be permanently deleted.\n\nDeleted data cannot be recovered.",
}


MANUAL_JA = {
    "널 플레이잉": "ナル・プレイング",
    "플레이하지 않아도, 모험은 진행 중.": "プレイしなくても、冒険は進んでいく。",
    "설정": "設定",
    "언어": "言語",
    "표시 언어를 선택하세요": "表示言語を選択してください",
    "영어": "英語",
    "일본어": "日本語",
    "한국어": "韓国語",
    "게임 화면으로 돌아가기": "ゲーム画面に戻る",
    "오프라인 모험 소진 알림": "オフライン冒険の終了通知",
    "오프라인 모험 충전 소진": "オフライン冒険時間が終了",
    "잔여 시간이 0이 되면 기기 알림": "残り時間が0になると通知します",
    "소진 알림 꺼짐": "終了通知はオフです",
    "기기 알림 권한을 허용해야 알림을 받을 수 있습니다.": "通知を受け取るには端末の通知権限を許可してください。",
    "기기 알림 권한이 필요합니다.": "通知権限が必要です。",
    "시스템 설정에서 기기 알림 권한이 꺼져 있습니다.": "システム設定で通知権限がブロックされています。",
    "시스템 설정에서 앱 알림이 꺼져 있습니다.": "システム設定でアプリの通知がオフになっています。",
    "시스템 알림 설정 열기": "システムの通知設定を開く",
    "시스템 알림 설정을 열지 못했습니다.": "システムの通知設定を開けませんでした。",
    "모험가 관리": "冒険者の管理",
    "모험가": "冒険者",
    "모험가 선택 화면으로": "冒険者選択画面へ",
    "모험가 선택 화면으로 이동": "冒険者選択画面へ移動",
    "{{1}}. {{2}}. 모험가 선택 화면으로 이동": "{{1}}。{{2}}。冒険者選択画面へ移動。",
    "모험가 화면으로 돌아가기": "冒険者画面に戻る",
    "모험가 삭제": "冒険者を削除",
    "모험가를 삭제할까요?": "この冒険者を削除しますか？",
    "게임 정보": "ゲーム情報",
    "개인정보처리방침": "プライバシーポリシー",
    "개인정보처리방침을 열지 못했습니다.": "プライバシーポリシーを開けませんでした。",
    "닫기": "閉じる",
    "익명 사용자 ID를 확인할 수 없습니다": "匿名ユーザーIDを確認できません",
    "저장된 익명 사용자와 서버 사용자가 일치하지 않습니다": "保存済みの匿名ユーザーとサーバーのユーザーが一致しません",
    "광고 개인정보 선택": "広告のプライバシー設定",
    "광고 개인정보 설정을 열지 못했습니다.": "広告のプライバシー設定を開けませんでした。",
    "버전 {{1}}": "バージョン {{1}}",
    "설정 화면에서도 자동 모험은 계속 진행됩니다.": "設定画面でも自動冒険は進行します。",
    "{{1}}의 오프라인 모험 시간이 모두 소진되었습니다.": "{{1}}のオフライン冒険時間がすべて終了しました。",
    "메인": "ホーム",
    "캐릭터": "キャラ",
    "장비": "装備",
    "가방": "バッグ",
    "퀘스트": "クエスト",
    "자동 진행 중": "自動進行中",
    "전투력": "戦闘力",
    "전투력 {{1}}": "戦闘力 {{1}}",
    "레벨 {{1}}": "レベル {{1}}",
    "이어하기 ›": "続ける ›",
    "현재 모험": "現在の冒険",
    "오프라인 잔여": "オフライン残り",
    "내 순위": "自分の順位",
    "전체 랭킹": "総合ランキング",
    "호칭": "称号",
    "순위 없음": "順位なし",
    "순위 미집계": "未集計",
    "순위 집계 중": "順位集計中",
    "유일한 왕좌": "唯一の覇者",
    "왕좌에 닿은 자": "王座に至りし者",
    "천상의 수호자": "天上の守護者",
    "전설의 선봉": "伝説の先鋒",
    "별을 베는 자": "星を断つ者",
    "불굴의 정복자": "不屈の征服者",
    "황금의 개척자": "黄金の開拓者",
    "새벽의 추적자": "暁の追跡者",
    "은빛의 영웅": "銀の英雄",
    "별빛의 계승자": "星明かりの継承者",
    "황금의 선구자": "黄金の先駆者",
    "은빛 추적자": "銀の追跡者",
    "청동 길잡이": "青銅の案内人",
    "별빛의 도전자": "星明かりの挑戦者",
    "새벽의 모험가": "暁の冒険者",
    "여정을 걷는 자": "旅路を歩む者",
    "다시 시도": "再試行",
    "확인": "確認",
    "보기": "表示",
    "랭킹을 불러오는 중": "ランキングを読み込み中",
    "모험가 랭킹": "冒険者ランキング",
    "능력치": "能力値",
    "능력치 안내": "能力値ガイド",
    "모든 직업에 적용되는 효과입니다.": "どの職業でも得られる効果です。",
    "직업의 주·보조 능력치는 공격력·전투력과 기본 스킬 발동률에도 영향을 줍니다.": "職業の主能力値・補助能力値は、攻撃力・戦闘力や基本スキル発動率にも影響します。",
    "STR · 힘": "STR · 筋力",
    "CON · 체력": "CON · 体力",
    "DEX · 민첩": "DEX · 敏捷性",
    "INT · 지능": "INT · 知力",
    "WIS · 지혜": "WIS · 知恵",
    "CHA · 매력": "CHA · 魅力",
    "HP MAX · 최대 HP": "HP MAX · 最大HP",
    "MP MAX · 최대 MP": "MP MAX · 最大MP",
    "가방에 더 많은 전리품을 담을 수 있습니다.": "バッグに入る戦利品の数が増えます。",
    "오프라인 모험시간이 늘어나고, 최대 HP 성장에 도움이 됩니다.": "オフラインで冒険できる時間が延び、最大HPも成長しやすくなります。",
    "몬스터를 더 빨리 찾습니다.": "モンスターをより早く見つけられます。",
    "스킬이 더 자주 발동하며, 최대 MP 성장에 도움이 됩니다.": "スキルが発動しやすくなり、最大MPも成長しやすくなります。",
    "전리품을 더 높은 가격에 판매합니다.": "戦利品をより高く売れるようになります。",
    "CON에 따라 성장하는 최대 체력입니다.": "CONに応じて成長する、体力の最大値です。",
    "INT와 WIS에 따라 성장하는 최대 마나입니다.": "INTとWISに応じて成長する、マナの最大値です。",
    "스킬": "スキル",
    "장착 장비": "装備中",
    "현재 깊이": "現在の深度",
    "최고 완주 깊이": "最深到達",
    "지난 모험담": "過去の冒険譚",
    "완결된 이야기": "完結した物語",
    "완결": "完結",
    "전리품": "戦利品",
    "획득 완료": "獲得済み",
    "모험의 서막": "冒険の序幕",
    "새로운 모험": "新しい冒険",
    "모험가 생성": "冒険者を作成",
    "모험가 이름 (2~8자)": "冒険者名（2～8文字）",
    "아직 모험가가 없습니다": "まだ冒険者がいません",
    "첫 모험가를 만들어 멈춰 있던 세계를 깨워 보세요.": "最初の冒険者を作り、止まっていた世界を目覚めさせましょう。",
    "직업 선택": "クラスを選択",
    "능력치 굴림": "能力値決定",
    "이 능력치로 모험 시작": "この能力値で冒険を始める",
    "주 능력치": "主要",
    "보조 능력치": "副",
    "다음 모험가 슬롯 · Lv.{{1}}에 영구 해금": "次の冒険者枠 · Lv.{{1}}で永久解放",
    "아래로 스크롤": "下にスクロール",
    "아래에 더 많은 모험 기록이 있습니다": "この下にも冒険記録があります",
    "다시 굴리기": "振り直す",
    "이전": "前へ",
    "다음": "次へ",
    "나중에": "あとで",
    "업데이트하기": "アップデート",
    "계속하려면 업데이트가 필요합니다.": "続行するにはアップデートが必要です。",
    "업데이트 페이지를 열지 못했습니다": "アップデートページを開けませんでした",
    "다시 불러오기": "再読み込み",
    "모험 기록 확인 필요": "冒険記録を確認してください",
    "모험 기록을 불러오는 중": "冒険記録を読み込み中",
    "지난 시간의 모험을 계산하는 중": "不在中の冒険を計算中",
    "모험 기록을 정리하는 중": "冒険記録を保存中",
    "모험을 시작하는 중": "冒険を開始中",
    "모험 기록을 확인하는 중": "冒険記録を確認中",
    "모험 기록을 안전하게 준비하고 있습니다": "冒険記録を安全に準備しています",
    "오프라인 모험 충전": "オフライン冒険時間",
    "바로 충전": "今すぐ充電",
    "충전 완료": "充電完了",
    "가득 차면 자동 귀환": "満杯になると自動帰還",
    "보유한 스킬이 없습니다.": "習得したスキルはありません。",
    "첫 전리품을 기다리는 중입니다.": "最初の戦利品を待っています。",
    "타이틀로 돌아가기": "タイトルに戻る",
    "모험가 선택으로 돌아가기": "冒険者選択に戻る",
    "캐릭터 화면으로 돌아가기": "キャラクター画面に戻る",
    "상단 배너 광고 320x50dp": "上部バナー広告、320×50dp",
    "전사": "戦士",
    "도적": "ローグ",
    "순찰자": "レンジャー",
    "마법사": "魔術師",
    "성직자": "聖職者",
    "성기사": "聖騎士",
    "파이터": "ファイター",
    "시프": "シーフ",
    "레인져": "レンジャー",
    "레인저": "レンジャー",
    "메이지": "メイジ",
    "클래릭": "クレリック",
    "팔라딘": "パラディン",
    "무기": "武器",
    "머리": "頭",
    "몸": "胴",
    "손": "手",
    "발": "足",
    "장신구": "装飾品",
    "일반": "ノーマル",
    "고급": "アンコモン",
    "희귀": "レア",
    "영웅": "エピック",
    "전설": "伝説",
    "신화": "神話",
    "정예": "エリート",
    "보스": "ボス",
    "서막": "序幕",
    "전투": "戦闘",
    "아이템 획득": "アイテム獲得",
    "귀환": "帰還",
    "장비 선별": "装備選別",
    "전리품 판매": "戦利品販売",
    "장비 정비": "装備整備",
    "구매 결과": "購入結果",
    "장비 검토": "装備確認",
    "출정": "出発",
    "물리": "物理",
    "화염": "炎",
    "냉기": "氷",
    "번개": "雷",
    "비전": "秘術",
    "암흑": "闇",
    "맹독": "猛毒",
    "바람": "風",
    "대지": "大地",
    "신성": "神聖",
    "우주": "宇宙",
    "니아가 열어 준 밀수로를 통해 {{1}} 두 번째 새벽종을 되찾았다. 하지만 마지막 수레는 성채로 들어갔고, 한 번 울린 종이 하늘의 빛을 껐다.": "ニアが開いた密輸路を通って、{{1}}は二つ目の暁鐘を取り戻した。しかし最後の荷車は城塞へ入り、一度鳴った鐘が空の光を消した。",
    "{{1}} 빈 주조장이 만들어 낸 미완성 문지기를 멈추고 제{{2}}구역의 화로를 귀환종에서 옮긴 불꽃으로 봉인했다.": "{{1}}は、空の鋳造所が生み出した未完成の門番を止め、第{{2}}区域の炉を帰還鐘から移した炎で封印した。",
    "{{1}} 파문 속 망령을 해산하고 지워진 별자리의 마지막 좌표를 복원했다. 좌표는 국경의 폐쇄된 관측소를 가리켰다.": "{{1}}は波紋の中の亡霊を解放し、消された星座の最後の座標を復元した。座標は国境の閉鎖された観測所を指していた。",
    "유리 영웅은 지금까지 사용한 모든 기술과 장비를 흉내 내며 자신이 더 완전한 원본이라고 선언했다.": "ガラスの英雄は、これまで使われたあらゆる技と装備をまね、自分こそより完全なオリジナルだと宣言した。",
    "검은 천을 두른 수레들이 관처럼 보였지만, 바퀴 자국은 성채 쪽으로 깊게 파여 있었다.": "黒布をかぶせた荷車は棺のように見えたが、車輪の跡は城塞の方へ深く刻まれていた。",
    "가짜 발자국이 과거의 걸음만 흉내 낸다는 규칙을 찾아 현재의 길을 구분했다.": "偽の足跡は過去の歩みだけをまねるという規則を突き止め、現在の道を見分けた。",
    "세 줄이 사람의 발자국이 아니라 미궁이 흉내 낸 반복 자국임을 밝혀냈다.": "三本の跡は人の足跡ではなく、迷宮がまねた反復痕だと突き止めた。",
    "국경식 쇠말뚝과 라움식 유리끈이 서로 다른 방향으로 천막을 당겼다.": "国境式の鉄杭とラウム式のガラス紐が、天幕を互いに異なる方向へ引いていた。",
    "무너진 수레와 쇠사슬을 점거한 무리를 쓰러뜨려 귀환로를 연다.": "崩れた荷車と鎖を占拠した一団を倒し、帰還路を開く。",
    "둥지를 치우고 끊긴 매듭을 다시 이어 지상 신호를 회복했다.": "巣を片づけ、切れた結び目をつなぎ直して地上信号を回復した。",
    "버려진 조각들이 서로 붙어 원정대의 장비 모양을 흉내 냈다.": "捨てられた破片がつながり合い、遠征隊の装備の形をまねた。",
    "구조 규약을 흉내 낸": "構造規約をまねた",
    "내 순위 {{1}}위, {{2}}, 호칭 {{3}}, 전투력 {{4}}": "自分の順位は{{1}}位、{{2}}、称号{{3}}、戦闘力{{4}}",
    "내 순위 {{1}}, {{2}}, 호칭 {{3}}, 전투력 {{4}}": "自分の順位は{{1}}、{{2}}、称号{{3}}、戦闘力{{4}}",
    "{{1}}, {{2}}, 레벨 {{3}}, 전투력 ": "{{1}}、{{2}}、レベル{{3}}、戦闘力 ",
    "제{{1}}구역 · 제{{2}}관문 · {{3}}": "第{{1}}区域 · 第{{2}}関門 · {{3}}",
    "제{{1}} 수문장": "第{{1}}の門番",
    "{{1}} · 장비력 {{2}} · {{3}}": "{{1}} · 装備力{{2}} · {{3}}",
    "{{1}}, {{2}}, 레벨 {{3}}, ": "{{1}}、{{2}}、レベル{{3}}、",
    " {{1}}. {{2}}회 중 {{3}}회 완료. 자동 진행 중.": " {{1}}。{{2}}回中{{3}}回完了。自動進行中。",
    "{{1}} 스킬 {{2}}개 · 스킬을 누르면 즉시 재생": "{{1}}のスキル {{2}}個 · タップですぐ再生",
    "{{1}}회 중 {{2}}회 완료": "{{1}}回中{{2}}回完了",
    "랭킹 참가까지 레벨 20, 현재 레벨 {{1}}, {{2}}": "ランキング参加条件：Lv.20（現在Lv.{{1}}）、{{2}}",
    "{{1}} · {{2}}막  {{3}}": "{{1}} · 第{{2}}幕  {{3}}",
    "{{1}}, {{2}}막 {{3}}.": "{{1}}、第{{2}}幕 {{3}}。",
    "제{{1}}구역 관문지기 · {{2}}": "第{{1}}区域の門番 · {{2}}",
    "{{1}}, 스킬 경험치 {{2}}": "{{1}}、スキル経験値{{2}}",
    "호칭 {{1}}, 전투력 {{2}}": "称号{{1}}、戦闘力{{2}}",
    "제{{1}}구역 · {{2}}": "第{{1}}区域 · {{2}}",
    "제{{1}}권 · {{2}}": "第{{1}}巻 · {{2}}",
    "제{{1}}권 제{{2}}장": "第{{1}}巻 第{{2}}章",
    "{{1}}막 · {{2}}": "第{{1}}幕 · {{2}}",
    "{{1}}위, ": "{{1}}位、",
    "현재 장면 {{1}}, {{2}}": "現在のシーン：{{1}}、{{2}}",
    "제{{1}}장  {{2}}": "第{{1}}章  {{2}}",
    "매의 급강하": "鷹の急降下",
    "검댕 뿔토끼": "煤けた角ウサギ",
    "{{1}}의 둥지 부스러기": "{{1}}の巣材",
    "{{1}}의 발자국 석고": "{{1}}の足跡石膏型",
    "거미 독낭": "クモの毒嚢",
    "그림자보다 빠르게": "影より速く",
    "깊이의 무게": "深層の重み",
    "돌아오지 않은 순찰대": "帰還しなかった巡回隊",
    "재가 내리는 우물": "灰降る井戸",
    "종이 새가 물어온 이름": "紙の鳥が運んだ名前",
    "문 없는 예배당": "扉のない礼拝堂",
    "밀수꾼의 정직한 지도": "密輸人の正直な地図",
    "적의 깃발 아래": "敵の旗の下で",
    "잠들지 않는 성벽": "眠らぬ城壁",
    "서로 다른 두 개의 명령": "相反する二つの命令",
    "검은 종의 행렬": "黒い鐘の行列",
    "재의 성채": "灰の城塞",
    "새벽을 삼킨 왕": "暁を喰らった王",
    "국경에 다시 뜬 해": "国境に再び昇る太陽",
    "유리 잎이 가리킨 북쪽": "ガラスの葉が指した北",
    "발자국을 기억하는 숲": "足跡を記憶する森",
    "창문 속에 갇힌 목소리": "窓に閉じ込められた声",
    "사라진 봄의 지도": "消えた春の地図",
    "베른에게 닿지 못한 답장": "ベルンに届かなかった返書",
    "아무도 늙지 않는 정원": "誰も年老いない庭",
    "도둑맞은 봄의 물": "盗まれた春の水",
    "서로를 닮은 두 사람": "互いに似た二人",
    "백야가 시작된 탑": "白夜が始まった塔",
    "유리 심장의 진실": "ガラスの心臓の真実",
    "깨지는 숲의 밤": "森が破碎する夜",
    "유리 숲의 첫 번째 봄": "ガラスの森の最初の春",
    "전령의 부탁: 돌아오지 않은 순찰대를 찾아 국경 마을의 피난로를 열어라.": "使者の依頼：行方不明の巡回隊を探し、国境の村の避難路を開け。",
    "지워진 수신인": "消された受取人",
    "쫓기는 전령": "追われる伝令",
    "종지기 오르반": "鐘守オルバン",
    "벽뿐인 예배당": "壁だけの礼拝堂",
    "세관 아래의 길": "税関の下の道",
    "돌아오지 못한 밀수꾼": "帰還できなかった密輸人",
    "서문을 지킨 이름들": "西門を守った者たち",
    "같은 날의 명령서": "同日に出された命令書",
    "사라진 서기관": "消えた書記官",
    "보호라는 변명": "「守るため」という言い訳",
    "성채로 향한 이름": "城塞へ向かった名",
    "천 아래의 종": "布の下の鐘",
    "끊어진 추격로": "途切れた追跡路",
    "빈 병영": "無人の兵舎",
    "잘못된 수호자": "誤れる守護者",
    "꺼진 하늘": "消えた空",
    "되돌아온 길들": "再び開かれた道々",
    "함께 울린 종": "共に鳴らした鐘",
    "돌아온 새벽": "戻った暁",
    "세 번의 불빛": "三度の光",
    "지도 밖의 북방길": "地図の外の北路",
    "앞서 간 발자국": "先行する足跡",
    "어제인 채 남은 야영지": "昨日のままの野営地",
    "이름을 잃은 대답": "名前を失った答え",
    "계절 지하실의 파수자": "季節地下室の番人",
    "얼어붙은 우편낭": "凍った郵便袋",
    "도착하지 않은 구원": "届かなかった救援",
    "답장을 삼킨 봉인": "返書を呑んだ封印",
    "멈춘 정오": "止まった正午",
    "되풀이되는 동의": "繰り返される同意",
    "거꾸로 흐르는 강": "逆流する川",
    "유리를 만드는 물레": "ガラスを作る水車",
    "빙결 수문장": "氷結の水門番",
    "해 지지 않는 계단": "日の沈まない階段",
    "세 불빛의 주인": "三つの光の主",
    "틀린 음의 합주": "狂った音の合奏",
    "길이 된 봄물": "道となった春の水",
    "나이테 회랑": "年輪の回廊",
    "숨 쉬는 길": "呼吸する道",
    "드러난 서고": "露わになった書庫",
    "잠든 공명핵": "眠れる共鳴核",
    "걸어 다니는 쇳조각": "歩く鉄屑",
    "화로의 약탈자": "炉の略奪者",
    "봉인된 화로": "封印された炉",
    "기억을 흐리는 꽃가루": "記憶を曇らせる花粉",
    "재꽃을 지키는 것": "灰の花を守るもの",
    "꽃 속의 얼굴": "花の中の顔",
    "지상 흙의 원": "地上土の輪",
    "방향을 잃은 첫 단": "方向を失った第一段",
    "나선의 끝문": "螺旋の終門",
    "{{1}}, {{2}}, 레벨 {{3}}, 전투력 {{4}}, 현재 모험 {{5}}, 오프라인 모험 잔여 {{6}}퍼센트, 이어하기": "{{1}}、{{2}}、レベル{{3}}、戦闘力{{4}}、現在の冒険：{{5}}、オフライン冒険残り{{6}}％、続ける",
    "오프라인 모험 시간이 가득 찼습니다": "オフライン冒険時間は満タンです。",
    "예정": "予定",
    "잠김": "ロック",
    "죽은 자의 명령": "死者の命令",
    "{{1}}에게 도착한 다음 날의 명령": "{{1}}に届いた翌日の命令",
    "죽은 자에게 도착한 다음 날의 명령": "死者に届いた翌日の命令",
    "비에 젖지 않는 종이 새가 날아와 {{1}}의 발치에서 스스로 펼쳐졌다.": "雨に濡れない紙の鳥が飛んできて、{{1}}の足元でひとりでに広がった。",
    "펼쳐짐. 두 번 탭하여 접기.": "展開中。ダブルタップで折りたたむ。",
    "접힘. 두 번 탭하여 펼치기.": "折りたたみ中。ダブルタップで展開。",
    "아직 시작되지 않음.": "まだ始まっていない。",
    "앞의 장면이 아직 끝나지 않음.": "前のシーンがまだ終わっていない。",
    "모험식": "冒険者式",
    "정규군식": "正規軍式",
    "개량 전투식": "改良戦闘式",
    "숙련 전투식": "熟練戦闘式",
    "기사단식": "騎士団式",
    "전승식": "伝承式",
    "용골 강화": "竜骨強化",
    "성유 각인": "聖油刻印",
    "마정석": "魔晶石",
    "성역식": "聖域式",
    "심층제": "深層製",
    "천공식": "天空式",
    "운명식": "運命式",
    "뿔투구": "角兜",
    "지휘관 투구": "指揮官の兜",
    "전사 건틀릿": "戦士のガントレット",
    "지휘관 판금화": "指揮官の板金靴",
    "용맹 브로치": "勇猛のブローチ",
    "전사 허리띠": "戦士のベルト",
    "파이터 투구": "ファイターの兜",
    "파이터 갑옷": "ファイターの鎧",
    "파이터 건틀릿": "ファイターのガントレット",
    "파이터 장화": "ファイターのブーツ",
    "파이터 허리띠": "ファイターのベルト",
    "시프 후드": "シーフの頭巾",
    "시프 가죽옷": "シーフの革装束",
    "시프 장갑": "シーフの手袋",
    "시프 장화": "シーフのブーツ",
    "시프 인장": "シーフの印章",
    "야행 머리띠": "夜行の鉒巻",
    "독니 목걸이": "毒牙の首飾り",
    "은신 브로치": "隠密のブローチ",
    "순찰자 두건": "レンジャーの頭巾",
    "매사냥 모자": "鷹匠の帽子",
    "순찰자 사냥복": "レンジャーの狩猟服",
    "레인져 창": "レンジャーの槍",
    "레인져 두건": "レンジャーの頭巾",
    "레인져 사냥복": "レンジャーの狩猟服",
    "레인저 창": "レンジャーの槍",
    "레인저 두건": "レンジャーの頭巾",
    "레인저 사냥복": "レンジャーの狩猟服",
    "매사냥 코트": "鷹匠のコート",
    "사냥 장갑": "狩猟用手袋",
    "활시위 손목띠": "弦の腕当て",
    "매사냥 장갑": "鷹匠の手袋",
    "순찰 전투화": "巡察の戦闘靴",
    "매눈 목걸이": "鷹の目の首飾り",
    "순찰 인장": "巡察の印章",
    "마도사 로브": "魔術師のローブ",
    "마도사 신발": "魔術師の靴",
    "메이지 관": "メイジの冠",
    "메이지 로브": "メイジのローブ",
    "메이지 신발": "メイジの靴",
    "마력 장갑": "魔力の手袋",
    "현자 손갑": "賢者の手甲",
    "수정 목걸이": "水晶の首飾り",
    "별빛 덧신": "星明かりの履物",
    "성가대 모자": "聖歌隊の帽子",
    "성유 손목띠": "聖油の腕輪",
    "신관 비단신": "神官の絹靴",
    "성상 목걸이": "聖像の首飾り",
    "성가 브로치": "聖歌のブローチ",
    "클래릭 관": "クレリックの冠",
    "클래릭 로브": "クレリックのローブ",
    "클래릭 완갑": "クレリックの腕甲",
    "클래릭 장화": "クレリックのブーツ",
    "클래릭 허리띠": "クレリックのベルト",
    "심판 망치": "審判の槌",
    "성기사 투구": "聖騎士の兜",
    "성기사 갑옷": "聖騎士の鎧",
    "성기사 건틀릿": "聖騎士のガントレット",
    "수호 철제신": "守護の鉄靴",
    "성휘 목걸이": "聖なる輝きの首飾り",
    "성전 브로치": "聖戦のブローチ",
    "성기사 허리띠": "聖騎士のベルト",
    "팔라딘 투구": "パラディンの兜",
    "팔라딘 갑옷": "パラディンの鎧",
    "팔라딘 건틀릿": "パラディンのガントレット",
    "팔라딘 장화": "パラディンのブーツ",
    "팔라딘 허리띠": "パラディンのベルト",
    "낡은": "古びた",
    "거친": "粗削りの",
    "소박한": "素朴な",
    "손질한": "手入れされた",
    "튼튼한": "丈夫な",
    "빛바랜": "色あせた",
    "상처 입은": "傷ついた",
    "길 잃은": "道に迷った",
    "배고픈": "腹を空かせた",
    "날카로운": "鋭い",
    "낮게 웅크린": "低く身を伏せた",
    "눈 밝은": "目ざとい",
    "제멋대로인": "気ままな",
    "숨을 죽인": "息を潜めた",
    "빠른": "素早い",
    "노련한": "手練れの",
    "무리를 이탈한": "群れを離れた",
    "밤을 노리는": "夜を狙う",
    "한쪽 눈의": "片目の",
    "거친 털의": "毛並みの荒い",
    "소리 없는": "音のない",
    "흔적을 감춘": "痕跡を隠した",
    "종이 새를 좇는": "紙の鳥を追う",
    "니아의 길을 좇는 자": "ニアの道を追う者",
    "쫓기는 편지의 탈취자": "追われる手紙の略奪者",
    "투명 껍질 딱정벌레": "透明な殻の甲虫",
    "투명하게 굳은 껍질의": "透明に固まった殻の",
    "봉인 나방": "封印のガ",
    "{{1}}막": "第{{1}}幕",
    "{{1}}의 잔해": "{{1}}の残骸",
    "{{1}} 표본": "{{1}}の標本",
    "{{1}}의 흔적": "{{1}}の痕跡",
    "{{1}}의 외피 조각": "{{1}}の外皮片",
    "{{1}}의 조직 표본": "{{1}}の組織標本",
    "{{1}}의 둥지 부스러기": "{{1}}の巣材",
    "{{1}}의 발자국 석고": "{{1}}の足跡石膏型",
    "{{1}}의 먹이 흔적": "{{1}}の食痕",
    "{{1}}의 재가루": "{{1}}の灰",
    "{{1}}의 생태 기록": "{{1}}の生態記録",
    "{{1}}의 활동 기록": "{{1}}の行動記録",
    "{{1}}의 탈피 조각": "{{1}}の抜け殻",
    "{{1}}의 선혈 표본": "{{1}}の血液標本",
    "{{1}}의 음영 스케치": "{{1}}のシルエット画",
    "{{1}}의 이동로 표식": "{{1}}の移動経路標識",
    "{{1}}의 관찰 일지": "{{1}}の観察記録",
    "{{1}} 발견": "{{1}}を発見",
    "발견했습니다": "発見",
    "‘{{1}}’의 레벨, 장비, 가방, 기술, 퀘스트를 포함한 모든 모험 기록이 영구 삭제됩니다.\n\n삭제한 기록은 복구할 수 없습니다.": "‘{{1}}’のレベル、装備、バッグ、スキル、クエストを含むすべての冒険記録が完全に削除されます。\n\n削除した記録は復元できません。",
    "‘{{1}}’의 레벨, 장비, 가방, 스킬, 퀘스트를 포함한 모든 모험 기록이 영구 삭제됩니다.\n\n삭제한 기록은 복구할 수 없습니다.": "‘{{1}}’のレベル、装備、バッグ、スキル、クエストを含むすべての冒険記録が完全に削除されます。\n\n削除した記録は復元できません。",
}


# Creature modifiers are composed with hundreds of monster names at runtime.  Keep these as
# connective, player-facing phrases instead of accepting literal machine translations.
MANUAL_EN.update({
    "검은 물띠를 휘감은": "Wrapped in Black Water Ribbons",
    "검은 유리 열쇠를 노리는": "Coveting the Black Glass Key",
    "검은 잉크를 흘리는": "Dripping Black Ink",
    "검은 장미를 휘감은": "Entwined with Black Roses",
    "검은 재와 흰 유리 사이의": "Between Black Ash and White Glass",
    "검은 천을 뒤집어쓴": "Draped in Black Cloth",
    "고정된 하강문을 노리는": "Stalking the Fixed Descent Gate",
    "공동 순찰로를 배회하는": "Roaming the Shared Patrol Route",
    "공동 천막을 노리는": "Stalking the Shared Camp",
    "공동묘지를 향하는": "Heading for the Communal Cemetery",
    "구조 규약을 흉내 낸": "Mimicking the Rescue Protocol",
    "군용 통로를 따르는": "Following the Military Passage",
    "군패 모서리를 피한": "Skirting the Military Tag's Edge",
    "귀환자의 보폭을 복제한": "Matching a Returner's Stride",
    "귀환종 신호를 쫓는": "Following the Return Bell Signal",
    "금 간 종소리에 멈춘": "Frozen at the Cracked Bell's Chime",
    "기록실에 깃든": "Haunting the Archive",
    "기억나무 뿌리에 감긴": "Entangled in the Memory Tree's Roots",
    "기억나무 아래에서 나온": "Emerged from Beneath the Memory Tree",
    "기억의 빛을 먹는": "Devouring the Light of Memory",
    "깊이 표식에 달라붙은": "Clinging to the Depth Marker",
    "꺼진 하늘 아래의": "Beneath the Darkened Sky",
    "끊긴 계단 끝의": "At the End of the Broken Stair",
    "끊긴 바퀴자국을 따라온": "Following the Broken Wheel Tracks",
    "끊어진 추격로에 숨은": "Hidden Along the Broken Pursuit Trail",
    "끝문 아래에서 나온": "Emerged from Beneath the Final Gate",
    "나이테 깊은 곳에서 나온": "Emerged from Deep Within the Tree Rings",
    "낮은 곳에서 올라온": "Risen from Below",
    "낯선 불씨를 따라온": "Following a Strange Ember",
    "낯선 장화자국을 따른": "Following Unfamiliar Bootprints",
    "네 번째 음에 멈춘": "Stilled at the Fourth Note",
    "녹슨 수레축을 물은": "Biting a Rusted Cart Axle",
    "다리 그늘에 납작 엎드린": "Crouched Low in the Bridge's Shadow",
    "다섯 개 매듭을 물은": "Clutching Five Knots",
    "마지막 봉인 너머의": "Beyond the Final Seal",
    "마지막 재에서 피어난": "Bloomed from the Last Ashes",
    "망치질 박자에 맞춰 움직이는": "Moving to the Hammer's Rhythm",
    "먼지 위에 새로 생긴": "Newly Formed in the Dust",
    "메아리 주물틀에서 나온": "Cast from the Echo Mold",
    "묘표 그늘을 도는": "Circling the Grave Marker's Shadow",
    "물속 얼굴을 훔친": "Wearing a Face Stolen from the Water",
    "밀수로에 납작 엎드린": "Crouched Low in the Smuggling Tunnel",
    "바퀴자국에 숨은": "Hidden in the Wheel Tracks",
    "버려진 적기를 휘감은": "Entwined with an Abandoned Enemy Flag",
    "벽화 아래 웅크린": "Crouched Beneath the Mural",
    "보급품 냄새를 맡은": "Drawn by the Scent of Supplies",
    "봉인된 계단을 지키는": "Guarding the Sealed Stair",
    "봉인을 난도질한": "Rending the Seal",
    "북방 표지석에 웅크린": "Crouched by the Northern Waystone",
    "북쪽 빛에 이끌린": "Drawn by the Northern Light",
    "북쪽 신호탑을 바라보는": "Watching the Northern Signal Tower",
    "불씨 씨앗을 품은": "Carrying an Ember Seed",
    "비밀 계단을 지키는": "Guarding the Secret Stair",
    "빈 병영을 배회하는": "Roaming the Empty Barracks",
    "빈 수레 밑에 숨은": "Hidden Beneath the Empty Cart",
    "빈 진지에 남은": "Left in the Abandoned Camp",
    "빈 초소를 배회하는": "Roaming the Empty Outpost",
    "빈 하늘을 등진": "With Its Back to the Empty Sky",
    "살아 움직이는 문에 숨은": "Hidden in the Living Door",
    "새로 난 길을 따르는": "Following the Newly Opened Path",
    "새벽빛에 흐려지는": "Fading in the Dawn Light",
    "새벽을 피한": "Shunning the Dawn",
    "서가 아래에 웅크린": "Crouched Beneath the Bookshelf",
    "서문을 들이받는": "Charging the West Gate",
    "성벽 안에 숨은": "Hidden Within the Walls",
    "성벽의 빛을 먹는": "Devouring the Wall's Light",
    "성채 안에서 기어나온": "Crawled Out of the Citadel",
    "성채에서 내려온": "Descended from the Citadel",
    "세 물길을 오가는": "Crossing the Three Waterways",
    "세 번째 불빛에 이끌린": "Drawn by the Third Light",
    "세 새벽종에 멈춘": "Stilled by the Three Dawn Bells",
    "세 종탑 사이를 오가는": "Moving Between the Three Bell Towers",
    "소리 없이 찬가하는": "Chanting a Soundless Hymn",
    "소리까지 반사하는": "Reflecting Even Sound",
    "손잡이 없는 벽에서 나온": "Emerged from the Handleless Wall",
    "수문 바닥에 붙은": "Clinging to the Sluice Floor",
    "수문 틈에 난": "Grown in a Sluice Gap",
    "수호대 군패를 물은": "Biting a Guardian Corps Tag",
    "수호자의 이름을 외우는": "Reciting the Guardian's Name",
    "순찰대를 따른": "Following the Patrol",
    "신호탑 그늘에 숨은": "Hidden in the Signal Tower's Shadow",
    "아래를 향한 거울에 비친": "Reflected in a Downward-Facing Mirror",
    "약속 없는 네 번째 빛에 깨어난": "Awakened by the Unpromised Fourth Light",
    "양군의 재를 먹은": "Feeding on Both Armies' Ashes",
    "열 번째 장에서 깨어난": "Awakened in Chapter Ten",
    "열세 번째 돌 아래의": "Beneath the Thirteenth Stone",
    "열여덟 울림에 답한": "Answering the Eighteenth Echo",
    "오래된 이름을 긁는": "Scratching at an Old Name",
    "오래된 종소리를 따르는": "Following the Ancient Bell",
    "우물 재를 먹은": "Feeding on Well Ash",
    "유리 나무 사이의": "Among the Glass Trees",
    "유리 뿌리를 감은": "Entwined with Glass Roots",
    "유리 잎을 물은": "Biting a Glass Leaf",
    "유리 파편을 깔고 다니는": "Trailing Glass Shards",
    "유품 사이에 숨은": "Hidden Among the Keepsakes",
    "은빛 단추를 물은": "Biting a Silver Button",
    "이름 닳은 군패를 물은": "Biting a Name-Worn Military Tag",
    "이름 씨앗을 노리는": "Stalking the Name Seed",
    "인장을 물어뜯은": "Gnawing at the Seal",
    "잉크 물결을 탄": "Riding the Ink Current",
    "잊힌 이름을 웅얼거리는": "Muttering Forgotten Names",
    "잊힌 이름을 읽는": "Reading a Forgotten Name",
    "잠긴 문장을 품은": "Bearing a Locked Sentence",
    "재 갑옷 틈에 숨은": "Hidden in the Ash Armor's Gaps",
    "재 갑옷을 두른": "Clad in Ash Armor",
    "재 아래에 뿌리내린": "Rooted Beneath the Ash",
    "재 지도에 남은": "Marked on the Ash Map",
    "재로 봉인된": "Sealed in Ash",
    "재와 유리 지도에 이끌린": "Guided by the Ash-and-Glass Map",
    "재의 파도에서 튀어나온": "Leaping from the Ash Wave",
    "잿물에 불은": "Swollen with Ashwater",
    "정기 보급로에 숨은": "Hidden Along the Supply Route",
    "종 쇠사슬을 끌고 다니는": "Dragging Bell Chains",
    "종 없는 울림에 깨어난": "Awakened by a Bell-Less Echo",
    "종가루를 털어 내는": "Shaking Off Bell Dust",
    "종소리 불꽃을 휘감은": "Wreathed in Bellfire",
    "종소리가 나면 멈추는": "Freezing When the Bell Rings",
    "종소리에 끌린": "Drawn by the Bell",
    "종소리에 홀린": "Bewitched by the Bell",
    "죽은 명령을 따르는": "Following a Dead Order",
    "중심 박동에 맞춰 움직이는": "Moving with the Core's Pulse",
    "지도에서 지워진": "Erased from the Map",
    "지워진 명부에 깃든": "Haunting the Erased Register",
    "지워진 이름 사이에 숨은": "Hidden Among Erased Names",
    "지워진 이름을 먹은": "Feeding on Erased Names",
    "지워진 줄에서 나온": "Emerged from an Erased Line",
    "지워진 층계를 배회하는": "Roaming the Erased Stairs",
    "지하에서 떠오른 푸른 빛을 두른": "Wreathed in Blue Light from Below",
    "짐수레를 휘감은": "Coiled Around a Cargo Cart",
    "천 개의 얼굴을 비춘": "Reflecting a Thousand Faces",
    "첫 계단에 웅크린": "Crouched on the First Step",
    "첫 구역 문턱에 웅크린": "Crouched at the First Sector's Threshold",
    "청동 가루를 뒤집어쓴": "Dusted with Bronze Powder",
    "청동 먼지를 뒤집어쓴": "Covered in Bronze Dust",
    "청동 빗물을 흘리는": "Dripping Bronze Rainwater",
    "출정 명부 주위를 맴도는": "Circling the Expedition Register",
    "탄화된 정원을 거니는": "Roaming the Charred Garden",
    "투명한 옥 깊은 곳의": "Deep Within the Clear Jade",
    "틀린 귀환 숫자를 남긴": "Leaving the Wrong Return Number",
    "푸른 아치를 휘감은": "Entwined Around the Blue Arch",
    "피난로를 가로막는": "Blocking the Evacuation Route",
    "회전하는 벽을 탄": "Riding the Rotating Wall",
})

MANUAL_JA.update({
    "검은 물띠를 휘감은": "黒い水帯をまとった",
    "검은 유리 열쇠를 노리는": "黒いガラスの鍵を狙う",
    "검은 잉크를 흘리는": "黒いインクを滴らせる",
    "검은 장미를 휘감은": "黒い薔薇をまとった",
    "검은 재와 흰 유리 사이의": "黒い灰と白いガラスの狭間にいる",
    "검은 천을 뒤집어쓴": "黒い布をかぶった",
    "고정된 하강문을 노리는": "固定された降下門を狙う",
    "공동 순찰로를 배회하는": "共同巡回路をさまよう",
    "공동 천막을 노리는": "共同野営地を狙う",
    "공동묘지를 향하는": "共同墓地へ向かう",
    "구조 규약을 흉내 낸": "救助規約をまねた",
    "군용 통로를 따르는": "軍用通路をたどる",
    "군패 모서리를 피한": "軍牌の縁を避けた",
    "귀환자의 보폭을 복제한": "帰還者の歩幅をまねた",
    "귀환종 신호를 쫓는": "帰還鐘の信号を追う",
    "금 간 종소리에 멈춘": "ひび割れた鐘の音で止まった",
    "기록실에 깃든": "記録室に巣食う",
    "기억나무 뿌리에 감긴": "記憶樹の根に絡まった",
    "기억나무 아래에서 나온": "記憶樹の下から現れた",
    "기억의 빛을 먹는": "記憶の光を食らう",
    "깊이 표식에 달라붙은": "深度標識に張り付いた",
    "꺼진 하늘 아래의": "消えた空の下の",
    "끊긴 계단 끝의": "途切れた階段の先の",
    "끊긴 바퀴자국을 따라온": "途切れた車輪跡をたどってきた",
    "끊어진 추격로에 숨은": "途切れた追跡路に隠れた",
    "끝문 아래에서 나온": "終端の門の下から現れた",
    "나이테 깊은 곳에서 나온": "年輪の奥深くから現れた",
    "낮은 곳에서 올라온": "低い場所から這い上がった",
    "낯선 불씨를 따라온": "見知らぬ火種を追ってきた",
    "낯선 장화자국을 따른": "見知らぬ長靴跡をたどる",
    "네 번째 음에 멈춘": "第四の音で止まった",
    "녹슨 수레축을 물은": "錆びた車軸をくわえた",
    "다리 그늘에 납작 엎드린": "橋の影に低く伏せた",
    "다섯 개 매듭을 물은": "五つの結び目をくわえた",
    "마지막 봉인 너머의": "最後の封印の向こうの",
    "마지막 재에서 피어난": "最後の灰から咲いた",
    "망치질 박자에 맞춰 움직이는": "槌音の拍子に合わせて動く",
    "먼지 위에 새로 생긴": "塵の上に生まれた",
    "메아리 주물틀에서 나온": "残響の鋳型から現れた",
    "묘표 그늘을 도는": "墓標の影を巡る",
    "물속 얼굴을 훔친": "水中の顔を盗んだ",
    "밀수로에 납작 엎드린": "密輸路に低く伏せた",
    "바퀴자국에 숨은": "車輪跡に隠れた",
    "버려진 적기를 휘감은": "捨てられた敵旗をまとった",
    "벽화 아래 웅크린": "壁画の下にうずくまる",
    "보급품 냄새를 맡은": "補給品の匂いを嗅ぎつけた",
    "봉인된 계단을 지키는": "封印された階段を守る",
    "봉인을 난도질한": "封印を切り裂いた",
    "북방 표지석에 웅크린": "北方の道標にうずくまる",
    "북쪽 빛에 이끌린": "北の光に導かれた",
    "북쪽 신호탑을 바라보는": "北の信号塔を見つめる",
    "불씨 씨앗을 품은": "火種の種を宿した",
    "비밀 계단을 지키는": "秘密の階段を守る",
    "빈 병영을 배회하는": "無人の兵舎をさまよう",
    "빈 수레 밑에 숨은": "空の荷車の下に隠れた",
    "빈 진지에 남은": "無人の陣地に残った",
    "빈 초소를 배회하는": "無人の詰所をさまよう",
    "빈 하늘을 등진": "空虚な空を背にした",
    "살아 움직이는 문에 숨은": "動く扉に潜む",
    "새로 난 길을 따르는": "新たに開いた道をたどる",
    "새벽빛에 흐려지는": "暁の光にかすむ",
    "새벽을 피한": "暁を避けた",
    "서가 아래에 웅크린": "書架の下にうずくまる",
    "서문을 들이받는": "西門へ突進する",
    "성벽 안에 숨은": "城壁の内側に隠れた",
    "성벽의 빛을 먹는": "城壁の光を食らう",
    "성채 안에서 기어나온": "城塞の中から這い出た",
    "성채에서 내려온": "城塞から降りてきた",
    "세 물길을 오가는": "三つの水路を行き来する",
    "세 번째 불빛에 이끌린": "三つ目の光に導かれた",
    "세 새벽종에 멈춘": "三つの暁鐘で止まった",
    "세 종탑 사이를 오가는": "三つの鐘楼を行き来する",
    "소리 없이 찬가하는": "音もなく賛歌を唱える",
    "소리까지 반사하는": "音さえ反射する",
    "손잡이 없는 벽에서 나온": "取っ手のない壁から現れた",
    "수문 바닥에 붙은": "水門の底に張り付いた",
    "수문 틈에 난": "水門の隙間に生えた",
    "수호대 군패를 물은": "守護隊の軍牌をくわえた",
    "수호자의 이름을 외우는": "守護者の名を唱える",
    "순찰대를 따른": "巡回隊を追う",
    "신호탑 그늘에 숨은": "信号塔の陰に隠れた",
    "아래를 향한 거울에 비친": "下向きの鏡に映った",
    "약속 없는 네 번째 빛에 깨어난": "約束なき第四の光で目覚めた",
    "양군의 재를 먹은": "両軍の灰を食らう",
    "열 번째 장에서 깨어난": "第十章で目覚めた",
    "열세 번째 돌 아래의": "十三番目の石の下の",
    "열여덟 울림에 답한": "十八の響きに応えた",
    "오래된 이름을 긁는": "古い名前を引っかく",
    "오래된 종소리를 따르는": "古い鐘の音をたどる",
    "우물 재를 먹은": "井戸の灰を食らう",
    "유리 나무 사이의": "ガラスの木々の間の",
    "유리 뿌리를 감은": "ガラスの根をまとった",
    "유리 잎을 물은": "ガラスの葉をくわえた",
    "유리 파편을 깔고 다니는": "ガラス片を引きずる",
    "유품 사이에 숨은": "遺品の間に隠れた",
    "은빛 단추를 물은": "銀のボタンをくわえた",
    "이름 닳은 군패를 물은": "名の擦れた軍牌をくわえた",
    "이름 씨앗을 노리는": "名前の種を狙う",
    "인장을 물어뜯은": "印章をかじった",
    "잉크 물결을 탄": "インクの波に乗る",
    "잊힌 이름을 웅얼거리는": "忘れられた名をつぶやく",
    "잊힌 이름을 읽는": "忘れられた名を読む",
    "잠긴 문장을 품은": "閉ざされた文を宿す",
    "재 갑옷 틈에 숨은": "灰の鎧の隙間に隠れた",
    "재 갑옷을 두른": "灰の鎧をまとった",
    "재 아래에 뿌리내린": "灰の下に根を張った",
    "재 지도에 남은": "灰の地図に記された",
    "재로 봉인된": "灰で封じられた",
    "재와 유리 지도에 이끌린": "灰とガラスの地図に導かれた",
    "재의 파도에서 튀어나온": "灰の波から飛び出した",
    "잿물에 불은": "灰水で膨れた",
    "정기 보급로에 숨은": "定期補給路に隠れた",
    "종 쇠사슬을 끌고 다니는": "鐘の鎖を引きずる",
    "종 없는 울림에 깨어난": "鐘なき響きで目覚めた",
    "종가루를 털어 내는": "鐘の粉を振り払う",
    "종소리 불꽃을 휘감은": "鐘火をまとった",
    "종소리가 나면 멈추는": "鐘が鳴ると止まる",
    "종소리에 끌린": "鐘の音に引かれた",
    "종소리에 홀린": "鐘の音に魅入られた",
    "죽은 명령을 따르는": "死者の命令に従う",
    "중심 박동에 맞춰 움직이는": "中心の鼓動に合わせて動く",
    "지도에서 지워진": "地図から消された",
    "지워진 명부에 깃든": "消された名簿に宿る",
    "지워진 이름 사이에 숨은": "消された名前の間に隠れた",
    "지워진 이름을 먹은": "消された名前を食らう",
    "지워진 줄에서 나온": "消された行から現れた",
    "지워진 층계를 배회하는": "消された階段をさまよう",
    "지하에서 떠오른 푸른 빛을 두른": "地下から昇る青い光をまとった",
    "짐수레를 휘감은": "荷車に巻き付いた",
    "천 개의 얼굴을 비춘": "千の顔を映した",
    "첫 계단에 웅크린": "最初の階段にうずくまる",
    "첫 구역 문턱에 웅크린": "第一区域の敷居にうずくまる",
    "청동 가루를 뒤집어쓴": "青銅の粉をかぶった",
    "청동 먼지를 뒤집어쓴": "青銅の塵をかぶった",
    "청동 빗물을 흘리는": "青銅色の雨水を滴らせる",
    "출정 명부 주위를 맴도는": "出征名簿の周りをさまよう",
    "탄화된 정원을 거니는": "炭化した庭を歩く",
    "투명한 옥 깊은 곳의": "透明な玉の奥深くの",
    "틀린 귀환 숫자를 남긴": "誤った帰還番号を残した",
    "푸른 아치를 휘감은": "青いアーチに巻き付いた",
    "피난로를 가로막는": "避難路を塞ぐ",
    "회전하는 벽을 탄": "回転する壁に乗る",
})

# Native game-name terminology used by the runtime name composer. These exact entries also keep
# fallback text, accessibility copy, and legacy saved presentation strings consistent.
MANUAL_EN.update({
    "장착 장비": "Equipped Gear",
    "뿔늑대": "Horned Wolf",
    "동굴 거미": "Cave Spider",
    "갑주 멧돼지": "Armored Boar",
    "잿빛 슬라임": "Ash Slime",
    "숲 고블린": "Forest Goblin",
    "돌가죽 트롤": "Stonehide Troll",
    "해골 기사": "Skeleton Knight",
    "그림자 박쥐": "Shadow Bat",
    "늪 히드라": "Marsh Hydra",
    "서리 와이번": "Frost Wyvern",
    "불꽃 정령": "Flame Spirit",
    "고대 골렘": "Ancient Golem",
    "심연 사냥개": "Abyss Hound",
    "독안개 만티코어": "Venom-Mist Manticore",
    "모래 리자드맨": "Sand Lizardman",
    "광산 코볼트": "Mine Kobold",
    "황혼 밴시": "Twilight Banshee",
    "천둥 그리핀": "Thunder Griffin",
    "혈월 오우거": "Bloodmoon Ogre",
    "공허 드레이크": "Void Drake",
    "문 없는 살쾡이": "Doorless Wildcat",
    "뿔늑대 송곳니": "Horned Wolf Fang",
    "수정 파편": "Crystal Shard",
    "검은 깃털": "Black Feather",
    "별가루": "Stardust",
    "용암 핵": "Magma Core",
    "은빛 비늘": "Silver Scale",
    "고대 톱니": "Ancient Gear",
    "유령 천": "Spectral Cloth",
    "거미 독낭": "Spider Venom Sac",
    "그리핀 발톱": "Griffin Talon",
    "정령 잔불": "Spirit Ember",
    "푸른 수액": "Azure Sap",
    "황혼 진주": "Twilight Pearl",
    "미스릴 조각": "Mithril Fragment",
    "봉인석": "Sealing Stone",
    "와이번 가죽": "Wyvern Hide",
    "심연의 눈": "Abyssal Eye",
    "골렘 심장": "Golem Heart",
    "달빛 버섯": "Moonlit Mushroom",
    "왕가의 인장": "Royal Sigil",
    "트롤 어금니": "Troll Tusk",
    "밴시의 눈물": "Banshee Tear",
    "천둥 결정": "Thunder Crystal",
    "붉은 모래": "Crimson Sand",
    "문장": "Crest",
    "가루병": "Powder Vial",
    "기념물": "Memento",
    "초월식": "Transcendent",
    "쌍날검": "Twinblade",
    "사슬모자": "Chain Helm",
    "지휘관 손목보호대": "Commander's Wristguards",
    "완갑": "Vambraces",
    "손갑": "Gauntlets",
    "주먹갑": "Fistguards",
    "쌍단검": "Twin Daggers",
    "암살 가면": "Assassin's Mask",
    "암살 조끼": "Assassin's Vest",
    "그림자 외투": "Shadow Cloak",
    "손가락 장갑": "Fingerless Gloves",
    "투척 장갑": "Throwing Gloves",
    "그림자 손갑": "Shadow Gauntlets",
    "단궁": "Shortbow",
    "궁술 장갑": "Archer's Gloves",
    "숲 손갑": "Forest Gauntlets",
    "명중 반지": "Ring of Accuracy",
    "화살통 허리띠": "Quiver Belt",
    "현자 후드": "Sage's Hood",
    "현자 의복": "Sage's Robes",
    "원소 장갑": "Elemental Gloves",
    "현자 장화": "Sage's Boots",
    "기도 머리띠": "Prayer Circlet",
    "성유 가면": "Consecrated Mask",
    "신관 관": "Priest's Circlet",
    "사제복": "Priest's Robes",
    "성유 망토": "Consecrated Cloak",
    "치유 장갑": "Healer's Gloves",
    "신관 손갑": "Priest's Gauntlets",
    "성유 장화": "Consecrated Boots",
    "수호 판금": "Guardian Plate",
    "왕실 갑주": "Royal Plate",
    "수호 손갑": "Guardian Gauntlets",
    "수호 부적": "Guardian Charm",
})

MANUAL_JA.update({
    "장착 장비": "装備中",
    "뿔늑대": "角狼",
    "동굴 거미": "洞窟グモ",
    "갑주 멧돼지": "装甲イノシシ",
    "잿빛 슬라임": "灰色スライム",
    "숲 고블린": "森ゴブリン",
    "돌가죽 트롤": "石肌トロール",
    "해골 기사": "骸骨騎士",
    "그림자 박쥐": "影コウモリ",
    "늪 히드라": "沼地ヒドラ",
    "서리 와이번": "フロストワイバーン",
    "불꽃 정령": "炎の精霊",
    "고대 골렘": "古代ゴーレム",
    "심연 사냥개": "深淵の猟犬",
    "독안개 만티코어": "毒霧マンティコア",
    "모래 리자드맨": "砂漠リザードマン",
    "광산 코볼트": "鉱山コボルト",
    "황혼 밴시": "黄昏のバンシー",
    "천둥 그리핀": "雷霆グリフォン",
    "혈월 오우거": "血月オーガ",
    "공허 드레이크": "ヴォイドドレイク",
    "문 없는 살쾡이": "門なしヤマネコ",
    "뿔늑대 송곳니": "角狼の牙",
    "수정 파편": "水晶の欠片",
    "검은 깃털": "黒羽",
    "별가루": "星屑",
    "용암 핵": "溶岩核",
    "은빛 비늘": "銀鱗",
    "고대 톱니": "古代の歯車",
    "유령 천": "霊布",
    "거미 독낭": "クモの毒袋",
    "그리핀 발톱": "グリフォンの鉤爪",
    "정령 잔불": "精霊の残り火",
    "푸른 수액": "青い樹液",
    "황혼 진주": "黄昏の真珠",
    "미스릴 조각": "ミスリル片",
    "봉인석": "封印石",
    "와이번 가죽": "ワイバーンの皮",
    "심연의 눈": "深淵の眼",
    "골렘 심장": "ゴーレムの心臓",
    "달빛 버섯": "月光キノコ",
    "왕가의 인장": "王家の印章",
    "트롤 어금니": "トロールの牙",
    "밴시의 눈물": "バンシーの涙",
    "천둥 결정": "雷の結晶",
    "붉은 모래": "赤砂",
    "문장": "紋章",
    "가루병": "粉末瓶",
    "기념물": "記念品",
    "초월식": "超越",
    "쌍날검": "双刃剣",
    "사슬모자": "チェーンヘルム",
    "지휘관 손목보호대": "指揮官のリストガード",
    "복면": "覆面",
    "야행 머리띠": "夜行の鉢巻",
    "그림자 모자": "影のフード",
    "손가락 장갑": "指ぬき手袋",
    "투척 장갑": "投擲手袋",
    "그림자 손갑": "影の手甲",
    "단궁": "短弓",
    "가죽 갑옷": "革鎧",
    "궁술 장갑": "弓術手袋",
    "숲 부적": "森の護符",
    "화살통 허리띠": "矢筒ベルト",
    "현자 후드": "賢者のフード",
    "기도 머리띠": "祈りの額飾り",
    "성유 가면": "聖別の仮面",
    "신관 관": "神官の冠",
    "사제복": "司祭のローブ",
    "성유 망토": "聖別の外套",
    "치유 장갑": "治癒の手袋",
    "신관 손갑": "神官の手甲",
    "성유 장화": "聖別のブーツ",
    "수호 판금": "守護者の板金鎧",
    "왕실 갑주": "王室の甲冑",
    "수호 부적": "守護の護符",
})


def decode_kotlin(value: str) -> str:
    result: list[str] = []
    index = 0
    escapes = {"n": "\n", "r": "\r", "t": "\t", '"': '"', "'": "'", "\\": "\\", "$": "$"}
    while index < len(value):
        if value[index] != "\\" or index + 1 >= len(value):
            result.append(value[index])
            index += 1
            continue
        next_char = value[index + 1]
        if next_char == "u" and index + 5 < len(value):
            try:
                result.append(chr(int(value[index + 2 : index + 6], 16)))
                index += 6
                continue
            except ValueError:
                pass
        result.append(escapes.get(next_char, "\\" + next_char))
        index += 2
    return "".join(result)


def scan_strings(source_root: Path) -> set[str]:
    values: set[str] = set()
    for path in sorted(source_root.rglob("*.kt")):
        # Internal matching keys classify authored monster names but are never rendered directly.
        if path.name == "MonsterModifierCompatibility.kt":
            continue
        source = path.read_text(encoding="utf-8")
        for match in TRIPLE_STRING.finditer(source):
            # Triple strings are table fixtures in SkillCatalog. Runtime displays their individual
            # pipe-delimited cells, never the complete multi-line table.
            for line in match.group(1).splitlines():
                for cell in line.split("|"):
                    cell = cell.strip()
                    if KOREAN.search(cell):
                        values.add(cell)
        source = TRIPLE_STRING.sub("", source)
        for match in STANDARD_STRING.finditer(source):
            value = decode_kotlin(match.group(1))
            if KOREAN.search(value):
                values.add(value)
    expanded: set[str] = set()
    for value in values:
        if "|" in value and not value.startswith(("^", "(?")):
            expanded.update(part.strip() for part in value.split("|") if KOREAN.search(part))
        else:
            expanded.add(value)
    return {value for value in expanded if value and value not in NON_DISPLAY_LITERALS}


def templateize(value: str) -> str:
    output: list[str] = []
    index = 0
    token_index = 1
    while index < len(value):
        if value.startswith("${", index):
            depth = 1
            cursor = index + 2
            while cursor < len(value) and depth:
                if value[cursor] == "{":
                    depth += 1
                elif value[cursor] == "}":
                    depth -= 1
                cursor += 1
            output.append(f"[990000{token_index}]")
            token_index += 1
            index = cursor
            continue
        if value[index] == "$" and index + 1 < len(value) and (value[index + 1].isalpha() or value[index + 1] == "_"):
            cursor = index + 2
            while cursor < len(value) and (value[cursor].isalnum() or value[cursor] == "_"):
                cursor += 1
            output.append(f"[990000{token_index}]")
            token_index += 1
            index = cursor
            continue
        match = PLAIN_PLACEHOLDER.match(value, index)
        if match:
            output.append(f"[990000{token_index}]")
            token_index += 1
            index = match.end()
            continue
        output.append(value[index])
        index += 1
    return "".join(output)


def catalog_template(value: str) -> str:
    value = MODEL_TOKEN.sub(lambda match: "{{" + match.group(1) + "}}", value)
    return LEGACY_TOKEN.sub(lambda match: "{{" + match.group(1) + "}}", value)


def model_template(value: str) -> str:
    return CATALOG_TOKEN.sub(lambda match: "[990000" + match.group(1) + "]", value)


class Translator:
    def __init__(self, model_path: Path):
        import ctranslate2
        import sentencepiece as spm

        self.sentencepiece = spm.SentencePieceProcessor(
            model_file=str(model_path / "spm.128k.model"),
        )
        self.translator = ctranslate2.Translator(
            str(model_path),
            device="cpu",
            compute_type="int8",
        )

    def translate(self, values: list[str], target: str) -> list[str]:
        translated: list[str] = []
        batch_size = 64
        for offset in range(0, len(values), batch_size):
            batch = values[offset : offset + batch_size]
            source_tokens = [
                ["__ko__"] + self.sentencepiece.encode(value, out_type=str)
                for value in batch
            ]
            results = self.translator.translate_batch(
                source_tokens,
                target_prefix=[[f"__{target}__"] for _ in batch],
                beam_size=1,
                max_batch_size=2_048,
                batch_type="tokens",
                max_decoding_length=128,
                repetition_penalty=1.2,
                no_repeat_ngram_size=3,
            )
            for result in results:
                tokens = result.hypotheses[0]
                if tokens and tokens[0] == f"__{target}__":
                    tokens = tokens[1:]
                translated.append(self.sentencepiece.decode(tokens).strip())
            print(
                f"{target}: {min(offset + batch_size, len(values))}/{len(values)}",
                flush=True,
            )
        return translated

    def translate_all(self, values: list[str]) -> tuple[list[str], list[str]]:
        english = self.translate(values, "en")
        japanese = self.translate(values, "ja")
        return english, japanese


def b64(value: str) -> str:
    return base64.b64encode(value.encode("utf-8")).decode("ascii")


def load_existing_catalog(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    existing: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"):
            continue
        parts = line.split("\t")
        if len(parts) != 3:
            raise RuntimeError(f"Invalid existing catalog row in {path}")
        source = base64.b64decode(parts[1]).decode("utf-8")
        target = base64.b64decode(parts[2]).decode("utf-8")
        existing[source] = target
    return existing


def load_structured_review_overrides(paths: list[Path]) -> dict[str, dict[str, str]]:
    combined: dict[str, dict[str, str]] = {}
    for path in paths:
        payload = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(payload, dict):
            raise RuntimeError(f"Review override root must be an object: {path}")
        for source, targets in payload.items():
            if not isinstance(source, str) or not isinstance(targets, dict):
                raise RuntimeError(f"Invalid review override entry in {path}: {source!r}")
            if set(targets) != {"en", "ja"} or not all(
                isinstance(targets[language], str) and targets[language].strip()
                for language in ("en", "ja")
            ):
                raise RuntimeError(f"Review override requires non-empty en/ja targets: {source!r}")
            previous = combined.get(source)
            if previous is not None and previous != targets:
                raise RuntimeError(f"Conflicting review overrides for {source!r}")
            combined[source] = {"en": targets["en"], "ja": targets["ja"]}
    return combined


def validate_translations(
    language: str,
    sources: list[str],
    targets: list[str],
    manual: dict[str, str],
) -> None:
    problems: list[str] = []
    for source, target in zip(sources, targets):
        source = catalog_template(source)
        target = manual.get(source, catalog_template(target))
        source_tokens = set(re.findall(r"\{\{([1-9][0-9]*)}}", source))
        target_tokens = set(re.findall(r"\{\{([1-9][0-9]*)}}", target))
        if source_tokens != target_tokens:
            problems.append(f"placeholder mismatch: {source!r} -> {target!r}")
        if not target.strip():
            problems.append(f"empty translation: {source!r}")
        if "<unk>" in target.lower():
            problems.append(f"unknown translation token: {source!r}")
        if KOREAN.search(target):
            problems.append(f"untranslated Korean: {source!r} -> {target[:180]!r}")
        if len(target) > max(180, len(source) * 6):
            problems.append(f"runaway translation: {source!r} -> {target[:180]!r}")
    if problems:
        preview = "\n".join(problems[:20])
        raise RuntimeError(f"{language} catalog validation failed ({len(problems)}):\n{preview}")


def write_catalog(path: Path, sources: list[str], targets: list[str], manual: dict[str, str]) -> None:
    rows: list[tuple[str, str, str]] = []
    for source, target in zip(sources, targets):
        source_template = catalog_template(source)
        target_template = catalog_template(target)
        target_template = manual.get(source_template, target_template)
        row_type = "P" if "{{" in source_template else "E"
        rows.append((row_type, source_template, target_template or source_template))
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as output:
        output.write("# Generated by tools/localization/build_catalog.py; Base64 TSV.\n")
        for row_type, source, target in rows:
            output.write(f"{row_type}\t{b64(source)}\t{b64(target)}\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", type=Path)
    parser.add_argument("--project", type=Path, default=Path(__file__).resolve().parents[2])
    parser.add_argument("--refresh-existing", action="store_true")
    args = parser.parse_args()
    raw_sources = scan_strings(args.project / "app/src/simple/java")
    sources = sorted(
        {catalog_template(templateize(value)) for value in raw_sources},
        key=lambda value: (-len(value), value),
    )
    raw_root = args.project / "app/src/simple/res/raw"
    existing_en = load_existing_catalog(raw_root / "localization_en.tsv")
    existing_ja = load_existing_catalog(raw_root / "localization_ja.tsv")
    review_overrides_path = args.project / "tools/localization/review_overrides.json"
    review_overrides = (
        json.loads(review_overrides_path.read_text(encoding="utf-8"))
        if review_overrides_path.exists()
        else {}
    )
    quest_review_overrides = load_structured_review_overrides(
        sorted((args.project / "tools/localization").glob("quest_review_*.json")),
    )
    unknown_quest_sources = sorted(set(quest_review_overrides) - set(sources))
    if unknown_quest_sources:
        preview = "\n".join(repr(source) for source in unknown_quest_sources[:20])
        raise RuntimeError(
            f"Quest review overrides contain {len(unknown_quest_sources)} unknown sources:\n{preview}",
        )
    effective_manual_en = {
        **MANUAL_EN,
        **{source: targets["en"] for source, targets in quest_review_overrides.items()},
    }
    effective_manual_ja = {
        **MANUAL_JA,
        **{source: targets["ja"] for source, targets in quest_review_overrides.items()},
    }
    pending = []
    for source in sources:
        manually_translated = source in effective_manual_en and source in effective_manual_ja
        reviewed = source in review_overrides and all(
            language in review_overrides[source] for language in ("en", "ja")
        )
        missing_existing = source not in existing_en or source not in existing_ja
        if not manually_translated and not reviewed and (args.refresh_existing or missing_existing):
            pending.append(source)
    generated_en: dict[str, str] = {}
    generated_ja: dict[str, str] = {}
    if pending:
        if args.model is None:
            raise RuntimeError(
                f"{len(pending)} new strings require --model; existing reviewed rows were preserved",
            )
        translator = Translator(args.model)
        translation_inputs = [model_template(source) for source in pending]
        new_english, new_japanese = translator.translate_all(translation_inputs)
        generated_en = dict(zip(pending, new_english))
        generated_ja = dict(zip(pending, new_japanese))
    english = [
        effective_manual_en.get(
            source,
            review_overrides.get(source, {}).get("en", generated_en.get(source, existing_en.get(source, ""))),
        )
        for source in sources
    ]
    japanese = [
        effective_manual_ja.get(
            source,
            review_overrides.get(source, {}).get("ja", generated_ja.get(source, existing_ja.get(source, ""))),
        )
        for source in sources
    ]
    validate_translations("en", sources, english, effective_manual_en)
    validate_translations("ja", sources, japanese, effective_manual_ja)
    write_catalog(raw_root / "localization_en.tsv", sources, english, effective_manual_en)
    write_catalog(raw_root / "localization_ja.tsv", sources, japanese, effective_manual_ja)
    print(f"Wrote {len(sources)} entries per language.")


if __name__ == "__main__":
    main()
