#!/usr/bin/env python3
"""Generate the engine-side arena attack-name table from the reviewed source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
SOURCE = Path(__file__).with_name("arena_attack_names_review_20260908.json")
TARGET = (
    PROJECT_ROOT
    / "app/src/simple/java/com/nullplaying/engine/arena/ArenaAttackNameLocalization.kt"
)


def kotlin_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )
    return f'"{escaped}"'


def render() -> str:
    reviewed = json.loads(SOURCE.read_text(encoding="utf-8"))
    if len(reviewed) != 120:
        raise SystemExit(f"expected 120 reviewed attack names, found {len(reviewed)}")
    if any(set(translations) != {"en", "ja"} for translations in reviewed.values()):
        raise SystemExit("every attack name must have exactly one English and one Japanese value")
    if any(
        not isinstance(value, str) or not value.strip()
        for translations in reviewed.values()
        for value in translations.values()
    ):
        raise SystemExit("reviewed attack names must be non-empty strings")
    if len({entry["en"] for entry in reviewed.values()}) != len(reviewed):
        raise SystemExit("English attack names must be globally unique")
    if len({entry["ja"] for entry in reviewed.values()}) != len(reviewed):
        raise SystemExit("Japanese attack names must be globally unique")

    rows = []
    for korean, translations in reviewed.items():
        rows.append(
            "        "
            + kotlin_string(korean)
            + " to ArenaLocalizedAttackName("
            + kotlin_string(translations["en"])
            + ", "
            + kotlin_string(translations["ja"])
            + "),"
        )

    return "\n".join(
        [
            "package com.nullplaying.engine.arena",
            "",
            "// Generated by tools/localization/generate_arena_attack_name_catalog.py from the",
            "// reviewed arena_attack_names_review_20260908.json source. Do not edit by hand.",
            "internal data class ArenaLocalizedAttackName(val english: String, val japanese: String)",
            "",
            "internal object ArenaAttackNameLocalization {",
            "    val values: Map<String, ArenaLocalizedAttackName> = linkedMapOf(",
            *rows,
            "    )",
            "",
            "    init {",
            "        require(values.size == 120)",
            "        require(values.values.map(ArenaLocalizedAttackName::english).distinct().size == values.size)",
            "        require(values.values.map(ArenaLocalizedAttackName::japanese).distinct().size == values.size)",
            "    }",
            "",
            "    fun get(sourceName: String): ArenaLocalizedAttackName = requireNotNull(values[sourceName]) {",
            '        "Missing reviewed arena attack localization: $sourceName"',
            "    }",
            "}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in Kotlin table differs from the reviewed JSON source",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        if not TARGET.exists() or TARGET.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"generated arena attack-name catalog is stale: {TARGET}")
        return
    TARGET.write_text(generated, encoding="utf-8")


if __name__ == "__main__":
    main()
