// Generated by tools/vfx-lab/sync_warrior_sprites_to_android.py.
// The stable catalogId is the only key; display names must not be used for routing.
package com.alarmquest.ui

import androidx.annotation.DrawableRes
import com.alarmquest.R

internal const val WARRIOR_DETAILED_SPRITE_COLUMNS = 4
internal const val WARRIOR_DETAILED_SPRITE_ROWS = 4
internal const val WARRIOR_DETAILED_SPRITE_FRAME_COUNT = 16
internal const val WARRIOR_DETAILED_SPRITE_FRAME_DURATION_MILLIS = 62.5
internal const val WARRIOR_DETAILED_SPRITE_DURATION_MILLIS = 1_000

internal fun warriorDetailedSpriteFrameIndex(
    elapsedMillis: Int,
    reducedMotion: Boolean,
): Int? {
    if (reducedMotion) return if (elapsedMillis in 0 until 780) 8 else null
    if (elapsedMillis !in 0 until WARRIOR_DETAILED_SPRITE_DURATION_MILLIS) return null
    return (elapsedMillis * WARRIOR_DETAILED_SPRITE_FRAME_COUNT /
        WARRIOR_DETAILED_SPRITE_DURATION_MILLIS).coerceIn(
        0,
        WARRIOR_DETAILED_SPRITE_FRAME_COUNT - 1,
    )
}

@DrawableRes
internal fun warriorDetailedSpriteSheetAssetId(catalogId: String): Int? = when (catalogId) {
    "warrior_t01_c01" -> R.drawable.vfx16_warrior_t01_c01
    "warrior_t01_c02" -> R.drawable.vfx16_warrior_t01_c02
    "warrior_t01_c03" -> R.drawable.vfx16_warrior_t01_c03
    "warrior_t01_c04" -> R.drawable.vfx16_warrior_t01_c04
    "warrior_t01_c05" -> R.drawable.vfx16_warrior_t01_c05
    "warrior_t02_c01" -> R.drawable.vfx16_warrior_t02_c01
    "warrior_t02_c02" -> R.drawable.vfx16_warrior_t02_c02
    "warrior_t02_c03" -> R.drawable.vfx16_warrior_t02_c03
    "warrior_t02_c04" -> R.drawable.vfx16_warrior_t02_c04
    "warrior_t02_c05" -> R.drawable.vfx16_warrior_t02_c05
    "warrior_t03_c01" -> R.drawable.vfx16_warrior_t03_c01
    "warrior_t03_c02" -> R.drawable.vfx16_warrior_t03_c02
    "warrior_t03_c03" -> R.drawable.vfx16_warrior_t03_c03
    "warrior_t03_c04" -> R.drawable.vfx16_warrior_t03_c04
    "warrior_t03_c05" -> R.drawable.vfx16_warrior_t03_c05
    "warrior_t04_c01" -> R.drawable.vfx16_warrior_t04_c01
    "warrior_t04_c02" -> R.drawable.vfx16_warrior_t04_c02
    "warrior_t04_c03" -> R.drawable.vfx16_warrior_t04_c03
    "warrior_t04_c04" -> R.drawable.vfx16_warrior_t04_c04
    "warrior_t04_c05" -> R.drawable.vfx16_warrior_t04_c05
    "warrior_t05_c01" -> R.drawable.vfx16_warrior_t05_c01
    "warrior_t05_c02" -> R.drawable.vfx16_warrior_t05_c02
    "warrior_t05_c03" -> R.drawable.vfx16_warrior_t05_c03
    "warrior_t05_c04" -> R.drawable.vfx16_warrior_t05_c04
    "warrior_t05_c05" -> R.drawable.vfx16_warrior_t05_c05
    "warrior_t06_c01" -> R.drawable.vfx16_warrior_t06_c01
    "warrior_t06_c02" -> R.drawable.vfx16_warrior_t06_c02
    "warrior_t06_c03" -> R.drawable.vfx16_warrior_t06_c03
    "warrior_t06_c04" -> R.drawable.vfx16_warrior_t06_c04
    "warrior_t06_c05" -> R.drawable.vfx16_warrior_t06_c05
    "warrior_t07_c01" -> R.drawable.vfx16_warrior_t07_c01
    "warrior_t07_c02" -> R.drawable.vfx16_warrior_t07_c02
    "warrior_t07_c03" -> R.drawable.vfx16_warrior_t07_c03
    "warrior_t07_c04" -> R.drawable.vfx16_warrior_t07_c04
    "warrior_t07_c05" -> R.drawable.vfx16_warrior_t07_c05
    "warrior_t08_c01" -> R.drawable.vfx16_warrior_t08_c01
    "warrior_t08_c02" -> R.drawable.vfx16_warrior_t08_c02
    "warrior_t08_c03" -> R.drawable.vfx16_warrior_t08_c03
    "warrior_t08_c04" -> R.drawable.vfx16_warrior_t08_c04
    "warrior_t08_c05" -> R.drawable.vfx16_warrior_t08_c05
    "warrior_t09_c01" -> R.drawable.vfx16_warrior_t09_c01
    "warrior_t09_c02" -> R.drawable.vfx16_warrior_t09_c02
    "warrior_t09_c03" -> R.drawable.vfx16_warrior_t09_c03
    "warrior_t09_c04" -> R.drawable.vfx16_warrior_t09_c04
    "warrior_t09_c05" -> R.drawable.vfx16_warrior_t09_c05
    "warrior_t10_c01" -> R.drawable.vfx16_warrior_t10_c01
    "warrior_t10_c02" -> R.drawable.vfx16_warrior_t10_c02
    "warrior_t10_c03" -> R.drawable.vfx16_warrior_t10_c03
    "warrior_t10_c04" -> R.drawable.vfx16_warrior_t10_c04
    "warrior_t10_c05" -> R.drawable.vfx16_warrior_t10_c05
    "warrior_t11_c01" -> R.drawable.vfx16_warrior_t11_c01
    "warrior_t11_c02" -> R.drawable.vfx16_warrior_t11_c02
    "warrior_t11_c03" -> R.drawable.vfx16_warrior_t11_c03
    "warrior_t11_c04" -> R.drawable.vfx16_warrior_t11_c04
    "warrior_t11_c05" -> R.drawable.vfx16_warrior_t11_c05
    "warrior_t12_c01" -> R.drawable.vfx16_warrior_t12_c01
    "warrior_t12_c02" -> R.drawable.vfx16_warrior_t12_c02
    "warrior_t12_c03" -> R.drawable.vfx16_warrior_t12_c03
    "warrior_t12_c04" -> R.drawable.vfx16_warrior_t12_c04
    "warrior_t12_c05" -> R.drawable.vfx16_warrior_t12_c05
    "warrior_t13_c01" -> R.drawable.vfx16_warrior_t13_c01
    "warrior_t13_c02" -> R.drawable.vfx16_warrior_t13_c02
    "warrior_t13_c03" -> R.drawable.vfx16_warrior_t13_c03
    "warrior_t13_c04" -> R.drawable.vfx16_warrior_t13_c04
    "warrior_t13_c05" -> R.drawable.vfx16_warrior_t13_c05
    "warrior_t14_c01" -> R.drawable.vfx16_warrior_t14_c01
    "warrior_t14_c02" -> R.drawable.vfx16_warrior_t14_c02
    "warrior_t14_c03" -> R.drawable.vfx16_warrior_t14_c03
    "warrior_t14_c04" -> R.drawable.vfx16_warrior_t14_c04
    "warrior_t14_c05" -> R.drawable.vfx16_warrior_t14_c05
    "warrior_t15_c01" -> R.drawable.vfx16_warrior_t15_c01
    "warrior_t15_c02" -> R.drawable.vfx16_warrior_t15_c02
    "warrior_t15_c03" -> R.drawable.vfx16_warrior_t15_c03
    "warrior_t15_c04" -> R.drawable.vfx16_warrior_t15_c04
    "warrior_t15_c05" -> R.drawable.vfx16_warrior_t15_c05
    "warrior_t16_c01" -> R.drawable.vfx16_warrior_t16_c01
    "warrior_t16_c02" -> R.drawable.vfx16_warrior_t16_c02
    "warrior_t16_c03" -> R.drawable.vfx16_warrior_t16_c03
    "warrior_t16_c04" -> R.drawable.vfx16_warrior_t16_c04
    "warrior_t16_c05" -> R.drawable.vfx16_warrior_t16_c05
    "warrior_t17_c01" -> R.drawable.vfx16_warrior_t17_c01
    "warrior_t17_c02" -> R.drawable.vfx16_warrior_t17_c02
    "warrior_t17_c03" -> R.drawable.vfx16_warrior_t17_c03
    "warrior_t17_c04" -> R.drawable.vfx16_warrior_t17_c04
    "warrior_t17_c05" -> R.drawable.vfx16_warrior_t17_c05
    "warrior_t18_c01" -> R.drawable.vfx16_warrior_t18_c01
    "warrior_t18_c02" -> R.drawable.vfx16_warrior_t18_c02
    "warrior_t18_c03" -> R.drawable.vfx16_warrior_t18_c03
    "warrior_t18_c04" -> R.drawable.vfx16_warrior_t18_c04
    "warrior_t18_c05" -> R.drawable.vfx16_warrior_t18_c05
    "warrior_t19_c01" -> R.drawable.vfx16_warrior_t19_c01
    "warrior_t19_c02" -> R.drawable.vfx16_warrior_t19_c02
    "warrior_t19_c03" -> R.drawable.vfx16_warrior_t19_c03
    "warrior_t19_c04" -> R.drawable.vfx16_warrior_t19_c04
    "warrior_t19_c05" -> R.drawable.vfx16_warrior_t19_c05
    "warrior_t20_c01" -> R.drawable.vfx16_warrior_t20_c01
    "warrior_t20_c02" -> R.drawable.vfx16_warrior_t20_c02
    "warrior_t20_c03" -> R.drawable.vfx16_warrior_t20_c03
    "warrior_t20_c04" -> R.drawable.vfx16_warrior_t20_c04
    "warrior_t20_c05" -> R.drawable.vfx16_warrior_t20_c05
    else -> null
}
