// Generated by tools/vfx-lab/sync_signature_sprites_to_android.py.
// Stable catalogId routing mirrors tools/vfx-lab/data/signature-skills.json.
package com.nullplaying.ui

import androidx.annotation.DrawableRes
import com.nullplaying.R
import kotlin.math.roundToInt

internal const val DETAILED_SPRITE_FRAME_WIDTH = 361
internal const val DETAILED_SPRITE_FRAME_HEIGHT = 160

internal data class DetailedSpriteSheetSpec(
    @DrawableRes val assetId: Int,
    val columns: Int,
    val rows: Int,
    val frameCount: Int,
    val frameDurationMillis: Double,
    val impactFrameIndex: Int?,
    val impactMillis: Int?,
    val postImpactFrameDurationMillis: Double?,
    val finalFrameHoldMillis: Int,
    val fadeOutMillis: Int,
)

internal data class DetailedSpriteFrame(
    val index: Int,
    val alpha: Float,
)

private fun detailedSpriteAuthoredEndMillis(spec: DetailedSpriteSheetSpec): Int {
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    return if (impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null) {
        impactMillis + ((spec.frameCount - impactFrameIndex) * postImpactFrameDurationMillis).roundToInt()
    } else {
        (spec.frameCount * spec.frameDurationMillis).roundToInt()
    }
}

private fun detailedSpriteFrameStartMillis(spec: DetailedSpriteSheetSpec, frameIndex: Int): Int {
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    return if (impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null) {
        if (frameIndex < impactFrameIndex) {
            (frameIndex.toDouble() * impactMillis / impactFrameIndex).roundToInt()
        } else {
            impactMillis + ((frameIndex - impactFrameIndex) * postImpactFrameDurationMillis).roundToInt()
        }
    } else {
        (frameIndex * spec.frameDurationMillis).roundToInt()
    }
}

private fun detailedSpriteFadeFrameIndex(spec: DetailedSpriteSheetSpec): Int =
    if (spec.frameCount == 16) spec.frameCount - 2 else spec.frameCount - 1

internal fun detailedSpriteDurationMillis(spec: DetailedSpriteSheetSpec): Int =
    detailedSpriteAuthoredEndMillis(spec) +
        spec.finalFrameHoldMillis +
        spec.fadeOutMillis

internal fun detailedSpriteFrame(
    elapsedMillis: Int,
    spec: DetailedSpriteSheetSpec,
    reducedMotion: Boolean,
): DetailedSpriteFrame? {
    if (elapsedMillis < 0) return null
    if (reducedMotion) return if (elapsedMillis < 780) {
        DetailedSpriteFrame(index = minOf(8, spec.frameCount - 1), alpha = 1f)
    } else null
    val hideAt = detailedSpriteDurationMillis(spec)
    if (elapsedMillis >= hideAt) return null
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    val authoredFrameIndex = if (
        impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null
    ) {
        if (elapsedMillis < impactMillis) {
            (elapsedMillis * impactFrameIndex / impactMillis).coerceIn(0, impactFrameIndex - 1)
        } else {
            (impactFrameIndex + ((elapsedMillis - impactMillis) / postImpactFrameDurationMillis).toInt())
                .coerceIn(impactFrameIndex, spec.frameCount - 1)
        }
    } else {
        (elapsedMillis / spec.frameDurationMillis).toInt().coerceIn(0, spec.frameCount - 1)
    }
    val fadeFrameIndex = detailedSpriteFadeFrameIndex(spec)
    val fadeStart = detailedSpriteFrameStartMillis(spec, fadeFrameIndex)
    val frameIndex = minOf(authoredFrameIndex, fadeFrameIndex)
    val alpha = 1f - ((elapsedMillis - fadeStart).toFloat() / (hideAt - fadeStart).toFloat())
    return DetailedSpriteFrame(frameIndex, alpha.coerceIn(0f, 1f))
}

internal fun detailedSpriteSheetSpec(catalogId: String): DetailedSpriteSheetSpec? = when (catalogId) {
    "warrior_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t01_c01, 4, 4, 16, 62.5, null, null, null, 0, 0)
    "warrior_t02_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t02_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t03_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t03_c02, 4, 3, 12, 62.5, null, null, null, 100, 250)
    "warrior_t04_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t04_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t05_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t05_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t06_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t06_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t07_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t07_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t08_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t08_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t09_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t09_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t10_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t10_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t11_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t11_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t12_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t12_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t13_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t13_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t14_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t14_c03, 4, 4, 16, 62.5, 8, 800, 70.0, 0, 40)
    "warrior_t15_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t15_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t16_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t16_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "warrior_t17_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t17_c01, 4, 4, 16, 62.5, 8, 800, 70.0, 0, 40)
    "warrior_t18_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t18_c02, 4, 4, 16, 62.5, 8, 800, 70.0, 0, 40)
    "warrior_t19_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t19_c02, 4, 4, 16, 62.5, 8, 800, 70.0, 0, 40)
    "warrior_t20_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_warrior_t20_c01, 4, 4, 16, 62.5, 8, 800, 70.0, 0, 40)
    "rogue_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t01_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t02_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t02_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t03_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t03_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t04_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t04_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t05_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t05_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t06_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t06_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t07_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t07_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t08_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t08_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t09_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t09_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t10_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t10_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t11_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t11_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t12_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t12_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t13_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t13_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t14_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t14_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t15_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t15_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t16_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t16_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t17_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t17_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t18_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t18_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t19_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t19_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "rogue_t20_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_rogue_t20_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t01_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t02_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t02_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t03_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t03_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t04_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t04_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t05_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t05_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t06_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t06_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t07_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t07_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t08_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t08_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t09_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t09_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t10_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t10_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t11_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t11_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t12_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t12_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t13_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t13_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t14_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t14_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t15_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t15_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t16_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t16_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t17_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t17_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t18_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t18_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t19_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t19_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "ranger_t20_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_ranger_t20_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t01_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t02_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t02_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t03_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t03_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t04_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t04_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t05_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t05_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t06_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t06_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t07_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t07_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t08_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t08_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t09_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t09_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t10_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t10_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t11_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t11_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t12_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t12_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t13_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t13_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t14_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t14_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t15_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t15_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t16_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t16_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t17_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t17_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t18_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t18_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t19_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t19_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "mage_t20_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_mage_t20_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t01_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t02_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t02_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t03_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t03_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t04_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t04_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t05_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t05_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t06_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t06_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t07_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t07_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t08_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t08_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t09_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t09_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t10_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t10_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t11_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t11_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t12_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t12_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t13_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t13_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t14_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t14_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t15_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t15_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t16_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t16_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t17_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t17_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t18_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t18_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t19_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t19_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "cleric_t20_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_cleric_t20_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t01_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t01_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t02_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t02_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t03_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t03_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t04_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t04_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t05_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t05_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t06_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t06_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t07_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t07_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t08_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t08_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t09_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t09_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t10_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t10_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t11_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t11_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t12_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t12_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t13_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t13_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t14_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t14_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t15_c03" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t15_c03, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t16_c02" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t16_c02, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t17_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t17_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t18_c04" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t18_c04, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t19_c01" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t19_c01, 4, 4, 16, 62.5, null, null, null, 100, 250)
    "paladin_t20_c05" -> DetailedSpriteSheetSpec(R.drawable.vfx_sheet_paladin_t20_c05, 4, 4, 16, 62.5, null, null, null, 100, 250)
    else -> null
}
