-- Localized, remotely managed title-screen announcements.
-- No row is inserted here; an operator publishes content from Supabase by setting enabled = true.

create table if not exists public.app_announcements (
  id bigint generated by default as identity primary key,
  announcement_key text not null check (
    char_length(announcement_key) between 1 and 80
    and announcement_key ~ '^[a-z0-9][a-z0-9_-]*$'
  ),
  platform text not null default 'android' check (platform in ('android')),
  language_code text not null check (language_code in ('ko', 'en', 'ja')),
  title text not null check (char_length(btrim(title)) between 1 and 120),
  message text not null check (char_length(btrim(message)) between 1 and 5000),
  minimum_version_code integer not null default 1 check (minimum_version_code >= 1),
  maximum_version_code integer check (maximum_version_code >= minimum_version_code),
  display_type text not null default 'every_launch' check (
    display_type in ('once_after_install', 'every_launch', 'once_per_day')
  ),
  priority integer not null default 0 check (priority between -1000 and 1000),
  starts_at timestamptz not null default now(),
  ends_at timestamptz,
  enabled boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (announcement_key, language_code),
  check (ends_at is null or ends_at > starts_at)
);

create index if not exists app_announcements_active_lookup_idx
  on public.app_announcements (
    platform,
    language_code,
    enabled,
    priority desc,
    starts_at desc
  );

alter table public.app_announcements enable row level security;
revoke all on public.app_announcements from anon, authenticated;
grant select on public.app_announcements to anon, authenticated;

create policy "clients read currently active announcements"
  on public.app_announcements for select to anon, authenticated
  using (
    enabled
    and platform = 'android'
    and starts_at <= now()
    and (ends_at is null or ends_at > now())
  );

create or replace function public.set_app_announcement_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function public.set_app_announcement_updated_at() from public;

create trigger set_app_announcements_updated_at
before update on public.app_announcements
for each row execute function public.set_app_announcement_updated_at();
