#!/usr/bin/env python3
"""Promote the web-ready warrior 4x4 sheets into Android Q85 WebP resources.

The browser map remains the source of truth.  This script deliberately promotes
only the 100 warrior catalog IDs and generates the matching Kotlin resource map.
The source PNGs remain lossless; only the Android derivatives use lossy color
compression while preserving the alpha channel exactly.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
LAB = ROOT / "tools/vfx-lab"
APP_JS = LAB / "app.js"
DRAWABLE = ROOT / "app/src/simple/res/drawable-nodpi"
KOTLIN_MAP = ROOT / "app/src/simple/java/com/alarmquest/ui/WarriorDetailedSpriteAssets.kt"

ANDROID_WEBP_QUALITY = 85
ANDROID_WEBP_ALPHA_QUALITY = 100
ANDROID_WEBP_METHOD = 4

FAMILY_FOLDERS = {
    "c01": "warrior-cleave",
    "c02": "warrior-crush",
    "c04": "warrior-earth",
    "c05": "warrior-flurry",
}


def literal_entries(block: str) -> dict[str, str]:
    return dict(
        re.findall(
            r'\["(warrior_t\d{2}_c\d{2})",\s*"(custom-assets/[^"]+\.png)"\]',
            block,
        )
    )


def browser_source_map() -> dict[str, Path]:
    source = APP_JS.read_text(encoding="utf-8")
    charge_block = source.split("const CURRENT_CHARGE_SPRITES", 1)[1].split("]);", 1)[0]
    signature_block = source.split("const SIGNATURE_WARRIOR_SPRITES", 1)[1].split("]);", 1)[0]
    warrior_block = source.split("const WARRIOR_SPRITES", 1)[1].split("]);", 1)[0]

    relative: dict[str, str] = {}
    for tier in range(1, 21):
        tier_label = f"{tier:02d}"
        for candidate, folder in FAMILY_FOLDERS.items():
            catalog_id = f"warrior_t{tier_label}_{candidate}"
            relative[catalog_id] = f"custom-assets/{folder}/{catalog_id}.png"
    relative.update(literal_entries(charge_block))
    relative.update(literal_entries(warrior_block))
    relative.update(literal_entries(signature_block))

    expected = {
        f"warrior_t{tier:02d}_c{candidate:02d}"
        for tier in range(1, 21)
        for candidate in range(1, 6)
    }
    if set(relative) != expected:
        missing = sorted(expected - set(relative))
        extra = sorted(set(relative) - expected)
        raise SystemExit(f"warrior browser map mismatch: missing={missing}, extra={extra}")
    if "...CURRENT_CHARGE_SPRITES.keys()" not in source:
        raise SystemExit("warrior charge family is not in the browser ready Set")
    for candidate, folder in FAMILY_FOLDERS.items():
        marker = f'...warriorFamilySpriteEntries("{candidate}", "{folder}").map(([catalogId]) => catalogId)'
        if marker not in source:
            raise SystemExit(f"warrior family is not in the browser ready Set: {candidate}")
    return {catalog_id: LAB / path for catalog_id, path in relative.items()}


def signature_catalog_ids() -> list[str]:
    source = APP_JS.read_text(encoding="utf-8")
    signature_block = source.split("const SIGNATURE_WARRIOR_SPRITES", 1)[1].split("]);", 1)[0]
    catalog_ids = sorted(literal_entries(signature_block))
    if len(catalog_ids) != 20:
        raise SystemExit(f"expected 20 signature warrior sprites, found {len(catalog_ids)}")
    return catalog_ids


def validate_source(path: Path) -> None:
    if not path.is_file():
        raise SystemExit(f"missing browser-ready sprite: {path}")
    with Image.open(path) as image:
        if image.format != "PNG" or image.size != (1444, 640) or image.mode != "RGBA":
            raise SystemExit(
                f"invalid Detailed 16-frame sheet {path}: "
                f"format={image.format}, size={image.size}, mode={image.mode}"
            )


def write_android_webp(source: Path, destination: Path) -> None:
    temporary = destination.with_suffix(".tmp.webp")
    with Image.open(source) as image:
        source_rgba = image.convert("RGBA")
        source_alpha = source_rgba.getchannel("A").tobytes()
        source_rgba.save(
            temporary,
            format="WEBP",
            lossless=False,
            quality=ANDROID_WEBP_QUALITY,
            alpha_quality=ANDROID_WEBP_ALPHA_QUALITY,
            method=ANDROID_WEBP_METHOD,
            exact=False,
        )
    with Image.open(temporary) as image:
        if image.format != "WEBP" or image.size != (1444, 640) or image.mode != "RGBA":
            raise SystemExit(
                f"invalid Android sprite {temporary}: "
                f"format={image.format}, size={image.size}, mode={image.mode}"
            )
        if image.getchannel("A").tobytes() != source_alpha:
            raise SystemExit(f"Android sprite alpha mismatch: {temporary}")
    temporary.replace(destination)


def write_kotlin_map(catalog_ids: list[str]) -> None:
    rows = "\n".join(
        f'    "{catalog_id}" -> R.drawable.vfx16_{catalog_id}' for catalog_id in catalog_ids
    )
    content = f"""// Generated by tools/vfx-lab/sync_warrior_sprites_to_android.py.
// The stable catalogId is the only key; display names must not be used for routing.
package com.alarmquest.ui

import androidx.annotation.DrawableRes
import com.alarmquest.R

internal const val WARRIOR_DETAILED_SPRITE_COLUMNS = 4
internal const val WARRIOR_DETAILED_SPRITE_ROWS = 4
internal const val WARRIOR_DETAILED_SPRITE_FRAME_COUNT = 16
internal const val WARRIOR_DETAILED_SPRITE_FRAME_DURATION_MILLIS = 62.5
internal const val WARRIOR_DETAILED_SPRITE_DURATION_MILLIS = 1_000

internal fun warriorDetailedSpriteFrameIndex(
    elapsedMillis: Int,
    reducedMotion: Boolean,
): Int? {{
    if (reducedMotion) return if (elapsedMillis in 0 until 780) 8 else null
    if (elapsedMillis !in 0 until WARRIOR_DETAILED_SPRITE_DURATION_MILLIS) return null
    return (elapsedMillis * WARRIOR_DETAILED_SPRITE_FRAME_COUNT /
        WARRIOR_DETAILED_SPRITE_DURATION_MILLIS).coerceIn(
        0,
        WARRIOR_DETAILED_SPRITE_FRAME_COUNT - 1,
    )
}}

@DrawableRes
internal fun warriorDetailedSpriteSheetAssetId(catalogId: String): Int? = when (catalogId) {{
{rows}
    else -> null
}}
"""
    KOTLIN_MAP.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--signature-only",
        action="store_true",
        help="promote only the 20 reviewed signature warrior sheets",
    )
    args = parser.parse_args()

    sources = browser_source_map()
    if args.signature_only:
        signature_ids = signature_catalog_ids()
        sources = {catalog_id: sources[catalog_id] for catalog_id in signature_ids}
    catalog_ids = sorted(sources)
    DRAWABLE.mkdir(parents=True, exist_ok=True)

    source_bytes = 0
    android_bytes = 0
    for catalog_id in catalog_ids:
        source = sources[catalog_id]
        validate_source(source)
        destination = DRAWABLE / f"vfx16_{catalog_id}.webp"
        write_android_webp(source, destination)
        source_bytes += source.stat().st_size
        android_bytes += destination.stat().st_size

    if not args.signature_only:
        write_kotlin_map(catalog_ids)
    print(f"mode={'signature-only' if args.signature_only else 'all-warrior'}")
    print(f"promoted={len(catalog_ids)}")
    print(f"validated_png_bytes={source_bytes}")
    print(f"android_webp_quality={ANDROID_WEBP_QUALITY}")
    print(f"android_webp_alpha_quality={ANDROID_WEBP_ALPHA_QUALITY}")
    print(f"android_q85_webp_bytes={android_bytes}")
    print(f"q85_ratio={android_bytes / source_bytes:.6f}")
    if not args.signature_only:
        print(f"kotlin_map={KOTLIN_MAP.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
