#!/usr/bin/env python3
"""Promote the 120 reviewed web signature sheets into Android Q85 WebP resources."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[2]
LAB = ROOT / "tools/vfx-lab"
MANIFEST = LAB / "data/signature-skills.json"
DRAWABLE = ROOT / "app/src/simple/res/drawable-nodpi"
KOTLIN_MAP = ROOT / "app/src/simple/java/com/alarmquest/ui/DetailedSpriteAssets.kt"

ANDROID_WEBP_QUALITY = 85
ANDROID_WEBP_ALPHA_QUALITY = 100
ANDROID_WEBP_METHOD = 4


def load_manifest() -> list[dict]:
    payload = json.loads(MANIFEST.read_text(encoding="utf-8"))
    skills = payload.get("skills", [])
    ids = [skill["id"] for skill in skills]
    if len(skills) != 120 or len(set(ids)) != 120:
        raise SystemExit(f"expected 120 unique signature skills, found {len(skills)}/{len(set(ids))}")
    return skills


def validate_source(skill: dict) -> tuple[Path, bytes]:
    source = LAB / skill["source"]
    expected_size = (skill["columns"] * 361, skill["rows"] * 160)
    if not source.is_file():
        raise SystemExit(f"missing browser-ready sprite: {source}")
    with Image.open(source) as image:
        if image.format != "PNG" or image.size != expected_size or image.mode != "RGBA":
            raise SystemExit(
                f"invalid signature sheet {source}: format={image.format}, "
                f"size={image.size}, mode={image.mode}, expected={expected_size} RGBA PNG"
            )
        return source, image.getchannel("A").tobytes()


def resource_name(catalog_id: str) -> str:
    return f"vfx_sheet_{catalog_id}"


def kotlin_double(value: int | float) -> str:
    rendered = f"{float(value):g}"
    return rendered if "." in rendered else f"{rendered}.0"


def kotlin_nullable(value: int | float | None, *, as_double: bool = False) -> str:
    if value is None:
        return "null"
    return kotlin_double(value) if as_double else str(value)


def write_android_webp(source: Path, source_alpha: bytes, destination: Path, expected_size: tuple[int, int]) -> None:
    temporary = destination.with_suffix(".tmp.webp")
    with Image.open(source) as image:
        image.save(
            temporary,
            format="WEBP",
            lossless=False,
            quality=ANDROID_WEBP_QUALITY,
            alpha_quality=ANDROID_WEBP_ALPHA_QUALITY,
            method=ANDROID_WEBP_METHOD,
            exact=False,
        )
    with Image.open(temporary) as image:
        if image.format != "WEBP" or image.size != expected_size or image.mode != "RGBA":
            raise SystemExit(
                f"invalid Android sprite {temporary}: format={image.format}, "
                f"size={image.size}, mode={image.mode}"
            )
        if image.getchannel("A").tobytes() != source_alpha:
            raise SystemExit(f"Android sprite alpha mismatch: {temporary}")
    temporary.replace(destination)


def kotlin_content(skills: list[dict]) -> str:
    rows = "\n".join(
        f'    "{skill["id"]}" -> DetailedSpriteSheetSpec('
        f'R.drawable.{resource_name(skill["id"])}, {skill["columns"]}, {skill["rows"]}, '
        f'{skill["frameCount"]}, {kotlin_double(skill["frameDurationMillis"])}, '
        f'{kotlin_nullable(skill.get("impactFrameIndex"))}, '
        f'{kotlin_nullable(skill.get("impactMillis"))}, '
        f'{kotlin_nullable(skill.get("postImpactFrameDurationMillis"), as_double=True)}, '
        f'{skill["finalFrameHoldMillis"]}, {skill["fadeOutMillis"]})'
        for skill in skills
    )
    return f"""// Generated by tools/vfx-lab/sync_signature_sprites_to_android.py.
// Stable catalogId routing mirrors tools/vfx-lab/data/signature-skills.json.
package com.alarmquest.ui

import androidx.annotation.DrawableRes
import com.alarmquest.R
import kotlin.math.roundToInt

internal const val DETAILED_SPRITE_FRAME_WIDTH = 361
internal const val DETAILED_SPRITE_FRAME_HEIGHT = 160

internal data class DetailedSpriteSheetSpec(
    @DrawableRes val assetId: Int,
    val columns: Int,
    val rows: Int,
    val frameCount: Int,
    val frameDurationMillis: Double,
    val impactFrameIndex: Int?,
    val impactMillis: Int?,
    val postImpactFrameDurationMillis: Double?,
    val finalFrameHoldMillis: Int,
    val fadeOutMillis: Int,
)

internal data class DetailedSpriteFrame(
    val index: Int,
    val alpha: Float,
)

private fun detailedSpriteAuthoredEndMillis(spec: DetailedSpriteSheetSpec): Int {{
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    return if (impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null) {{
        impactMillis + ((spec.frameCount - impactFrameIndex) * postImpactFrameDurationMillis).roundToInt()
    }} else {{
        (spec.frameCount * spec.frameDurationMillis).roundToInt()
    }}
}}

private fun detailedSpriteFrameStartMillis(spec: DetailedSpriteSheetSpec, frameIndex: Int): Int {{
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    return if (impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null) {{
        if (frameIndex < impactFrameIndex) {{
            (frameIndex.toDouble() * impactMillis / impactFrameIndex).roundToInt()
        }} else {{
            impactMillis + ((frameIndex - impactFrameIndex) * postImpactFrameDurationMillis).roundToInt()
        }}
    }} else {{
        (frameIndex * spec.frameDurationMillis).roundToInt()
    }}
}}

private fun detailedSpriteFadeFrameIndex(spec: DetailedSpriteSheetSpec): Int =
    if (spec.frameCount == 16) spec.frameCount - 2 else spec.frameCount - 1

internal fun detailedSpriteDurationMillis(spec: DetailedSpriteSheetSpec): Int =
    detailedSpriteAuthoredEndMillis(spec) +
        spec.finalFrameHoldMillis +
        spec.fadeOutMillis

internal fun detailedSpriteFrame(
    elapsedMillis: Int,
    spec: DetailedSpriteSheetSpec,
    reducedMotion: Boolean,
): DetailedSpriteFrame? {{
    if (elapsedMillis < 0) return null
    if (reducedMotion) return if (elapsedMillis < 780) {{
        DetailedSpriteFrame(index = minOf(8, spec.frameCount - 1), alpha = 1f)
    }} else null
    val hideAt = detailedSpriteDurationMillis(spec)
    if (elapsedMillis >= hideAt) return null
    val impactFrameIndex = spec.impactFrameIndex
    val impactMillis = spec.impactMillis
    val postImpactFrameDurationMillis = spec.postImpactFrameDurationMillis
    val authoredFrameIndex = if (
        impactFrameIndex != null && impactMillis != null && postImpactFrameDurationMillis != null
    ) {{
        if (elapsedMillis < impactMillis) {{
            (elapsedMillis * impactFrameIndex / impactMillis).coerceIn(0, impactFrameIndex - 1)
        }} else {{
            (impactFrameIndex + ((elapsedMillis - impactMillis) / postImpactFrameDurationMillis).toInt())
                .coerceIn(impactFrameIndex, spec.frameCount - 1)
        }}
    }} else {{
        (elapsedMillis / spec.frameDurationMillis).toInt().coerceIn(0, spec.frameCount - 1)
    }}
    val fadeFrameIndex = detailedSpriteFadeFrameIndex(spec)
    val fadeStart = detailedSpriteFrameStartMillis(spec, fadeFrameIndex)
    val frameIndex = minOf(authoredFrameIndex, fadeFrameIndex)
    val alpha = 1f - ((elapsedMillis - fadeStart).toFloat() / (hideAt - fadeStart).toFloat())
    return DetailedSpriteFrame(frameIndex, alpha.coerceIn(0f, 1f))
}}

internal fun detailedSpriteSheetSpec(catalogId: String): DetailedSpriteSheetSpec? = when (catalogId) {{
{rows}
    else -> null
}}
"""


def prune_stale_resources(expected: set[Path]) -> int:
    candidates = set(DRAWABLE.glob("vfx16_*_t??_c??.webp"))
    candidates.update(DRAWABLE.glob("vfx_sheet_*_t??_c??.webp"))
    stale = sorted(candidates - expected)
    for path in stale:
        path.unlink()
    return len(stale)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check-only", action="store_true", help="validate the 120 web sources without writing")
    parser.add_argument("--prune", action="store_true", help="remove stale generated skill-sheet derivatives")
    args = parser.parse_args()

    skills = load_manifest()
    validated = [(skill, *validate_source(skill)) for skill in skills]
    source_bytes = sum(source.stat().st_size for _, source, _ in validated)
    if args.check_only:
        print(f"validated_sources={len(validated)}")
        print(f"validated_png_bytes={source_bytes}")
        return
    DRAWABLE.mkdir(parents=True, exist_ok=True)
    expected: set[Path] = set()
    android_bytes = 0
    for skill, source, source_alpha in validated:
        destination = DRAWABLE / f"{resource_name(skill['id'])}.webp"
        expected.add(destination)
        expected_size = (skill["columns"] * 361, skill["rows"] * 160)
        write_android_webp(source, source_alpha, destination, expected_size)
        android_bytes += destination.stat().st_size

    KOTLIN_MAP.write_text(kotlin_content(skills), encoding="utf-8")
    pruned = prune_stale_resources(expected) if args.prune else 0
    print(f"promoted={len(skills)}")
    print(f"validated_png_bytes={source_bytes}")
    print(f"android_webp_quality={ANDROID_WEBP_QUALITY}")
    print(f"android_webp_alpha_quality={ANDROID_WEBP_ALPHA_QUALITY}")
    print(f"android_q85_webp_bytes={android_bytes}")
    print(f"q85_ratio={android_bytes / source_bytes:.6f}")
    print(f"pruned_stale_derivatives={pruned}")
    print(f"kotlin_map={KOTLIN_MAP.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
